/* ── model-skills.ts ──
   Every chassis is a class, and every class plays the duel differently.

   The duel these are for is a music quiz: two players answer questions about
   notes, rhythm, intervals and scales, and the answers drive a fight. So the
   skills act on the QUIZ, not on some abstract battle — they buy time, strip a
   wrong option, protect the first mistake in a category, turn a streak into
   damage. A skill that only said "+20% damage" would be a stat in disguise;
   these change how a round is played, which is what makes picking RONIN feel
   different from picking PIP rather than just looking different.

   Three per model, in the usual shape: a PASSIVE that is always true, an ACTIVE
   on a cooldown, and an ULTIMATE once per duel. Icons reuse the item-art
   archetypes so the skill sheet is drawn in the same language as the shop.

   Balance note: the four combat stats already total the same 40 on every
   chassis (see MODEL_COMBAT). Skills are deliberately NOT balanced by raw
   number — they are balanced by condition. REAPER's passive is huge and only
   fires when the opponent is nearly down; KEEPER's is small and always on. ── */

export const MODEL_CLASS = {
  striker:   { th: "สายจู่โจม",   en: "Striker",   zh: "突击系", c: "#e0563f", art: "sword" },
  bulwark:   { th: "สายป้องกัน",  en: "Bulwark",   zh: "守护系", c: "#3d86c6", art: "shield" },
  ghost:     { th: "สายลอบเร้น",  en: "Ghost",     zh: "潜行系", c: "#7b3fd0", art: "eye" },
  tactician: { th: "สายวางแผน",   en: "Tactician", zh: "策略系", c: "#2fa87a", art: "scope" },
  engineer:  { th: "สายช่างกล",   en: "Engineer",  zh: "工程系", c: "#c98f2a", art: "wrench" },
  herald:    { th: "สายประสาน",   en: "Herald",    zh: "协奏系", c: "#c0603f", art: "speaker" },
  virtuoso:  { th: "สายบรรเลง",   en: "Virtuoso",  zh: "演奏系", c: "#d0559a", art: "keytar" },
};

export const TIER_LABEL = {
  passive:  { th: "ติดตัว",   en: "Passive",  zh: "被动" },
  active:   { th: "ใช้งาน",   en: "Active",   zh: "主动" },
  ultimate: { th: "ไม้ตาย",   en: "Ultimate", zh: "终极" },
};

const sk = (tier, art, th, en, zh, dth, den, dzh) =>
  ({ tier, art, n: { th, en, zh }, d: { th: dth, en: den, zh: dzh } });

export const MODEL_SKILLS = {
  /* ── STRIKERS ── the damage is real and so is the exposure */
  vanguard: { cls: "striker", skills: [
    sk("passive", "chip", "แรงส่งสะสม", "Momentum Rounds", "动量弹链",
       "ตอบถูกติดกัน ดาเมจ +8% ต่อครั้ง สูงสุด +40%",
       "Each answer right in a row adds 8% damage, up to 40%.",
       "连续答对每次伤害 +8%，最高 +40%。"),
    sk("active", "blaster", "ระดมยิง", "Suppressing Fire", "压制射击",
       "ยิงรัวหนึ่งชุด ดาเมจตามจำนวนข้อที่ตอบถูกในยกนี้",
       "A burst whose damage counts every question you got right this round.",
       "一轮扫射，伤害按本回合答对题数计算。"),
    sk("ultimate", "burst", "โหมดล่าสังหาร", "Termination Mode", "终结模式",
       "3 ข้อถัดไป ดาเมจ ×2 แต่ตอบผิดก็เสียเลือด ×2",
       "For three questions: double damage dealt, double damage taken on a miss.",
       "接下来三题：伤害翻倍，答错受伤也翻倍。") ] },
  reaper: { cls: "striker", skills: [
    sk("passive", "beam", "ไร้ปรานี", "Ruthless", "无情",
       "เมื่อเลือดคู่ต่อสู้ต่ำกว่า 40% ดาเมจ +25%",
       "Below 40% opponent health, your damage rises 25%.",
       "对手血量低于 40% 时，伤害 +25%。"),
    sk("active", "grenade", "ตัดวงจร", "Execute Protocol", "处决协议",
       "ดาเมจคิดจากเลือดที่คู่ต่อสู้เสียไปแล้ว ยิ่งเจ็บยิ่งแรง",
       "Damage scales with health the opponent has already lost.",
       "伤害按对手已损失的血量计算。"),
    sk("ultimate", "charge", "วงจรไหม้", "Scorched Circuit", "焦化回路",
       "เสียเลือดตัวเอง 15% เพื่อทำดาเมจ 40%",
       "Burn 15% of your own health to deal 40%.",
       "自损 15% 血量，造成 40% 伤害。") ] },
  ronin: { cls: "striker", skills: [
    sk("passive", "sword", "ไอไอโด", "Iaido", "居合",
       "ถ้าตอบถูกก่อนคู่ต่อสู้ ดาเมจ +30%",
       "Answer right before your opponent does and hit 30% harder.",
       "比对手先答对，伤害 +30%。"),
    sk("active", "cutter", "วิถีดาบเดียว", "Single Stroke", "一刀流",
       "ดาเมจมหาศาล แต่ตอบผิดคือพลาดทั้งตา",
       "Enormous damage — but a wrong answer wastes the whole turn.",
       "巨额伤害，但答错则整回合落空。"),
    sk("ultimate", "boomerang", "ระบำดาบ", "Blade Dance", "剑舞",
       "โจมตี 3 ครั้งติดกัน ครั้งละ 40% ของดาเมจปกติ",
       "Three strikes in a row at 40% damage each.",
       "连续三击，每击 40% 伤害。") ] },
  talon: { cls: "striker", skills: [
    sk("passive", "scope", "ไม่มีพลาด", "No Miss", "无失",
       "การโจมตีของคุณทะลุการหลบทุกชนิด",
       "Your attacks cannot be dodged.",
       "你的攻击无法被闪避。"),
    sk("active", "beam", "ล็อกเป้าหมาย", "Target Lock", "目标锁定",
       "2 ข้อถัดไป ดาเมจ +20% และทะลุโล่",
       "For two questions: 20% more damage, and shields do not stop it.",
       "接下来两题：伤害 +20%，无视护盾。"),
    sk("ultimate", "burst", "ห่วงโซ่สังหาร", "Kill Chain", "杀戮链",
       "ตอบถูกติด 3 ข้อ แล้วปล่อยดาเมจรวมทั้งหมดทีเดียว",
       "Chain three right answers, then release all of it at once.",
       "连答对三题后，一次性释放全部伤害。") ] },

  /* ── BULWARKS ── they win by still being there */
  sentinel: { cls: "bulwark", skills: [
    sk("passive", "shield", "เกราะเสริมแรง", "Hardened Plating", "强化装甲",
       "ดาเมจที่ได้รับลดลง 15% ตลอดการต่อสู้",
       "All damage taken is reduced by 15%.",
       "全程受到的伤害降低 15%。"),
    sk("active", "barrier", "ตั้งโล่กำบัง", "Bulwark Stance", "壁垒姿态",
       "ดูดซับดาเมจครั้งถัดไปทั้งหมด",
       "Absorb the next hit completely.",
       "完全吸收下一次伤害。"),
    sk("ultimate", "helm", "โปรโตคอลป้อมปราการ", "Fortress Protocol", "堡垒协议",
       "3 ข้อถัดไป ตอบผิดไม่เสียเลือด แต่ตอบถูกก็ไม่ทำดาเมจ",
       "Three questions where mistakes cost nothing — and right answers deal nothing.",
       "三题内答错不掉血，但答对也不造成伤害。") ] },
  atlas: { cls: "bulwark", skills: [
    sk("passive", "limb", "ไม่มีอะไรขยับได้", "Unmovable", "不动如山",
       "ไม่ติดผลลดความเร็วหรือลดเวลาตอบใดๆ",
       "Immune to every slow and every clock cut.",
       "免疫一切减速与缩时效果。"),
    sk("active", "shield", "ยืนรับแทน", "Take The Hit", "代为承受",
       "ดูดซับดาเมจ 2 ข้อ แล้วสะท้อนกลับครึ่งหนึ่ง",
       "Soak two questions' damage, then return half of it.",
       "吸收两题伤害，并反弹一半。"),
    sk("ultimate", "plate", "กำแพงไททัน", "Titan Wall", "泰坦之墙",
       "เลือดสูงสุด +30% และฟื้นเต็มส่วนที่เพิ่มมาทันที",
       "Raise max health 30% and immediately fill the new space.",
       "最大生命 +30%，并立刻填满新增部分。") ] },
  mochi: { cls: "bulwark", skills: [
    sk("passive", "plate", "นุ่มจนไม่เจ็บ", "Squish", "软化",
       "ดาเมจที่รับต่อครั้งไม่เกิน 12% ของเลือดสูงสุด",
       "No single hit can take more than 12% of your health.",
       "单次受伤不超过最大生命的 12%。"),
    sk("active", "orb", "ดูดซับแรงกระแทก", "Squish Absorb", "软化吸收",
       "เก็บดาเมจที่รับไว้ แล้วคืนกลับเป็นเลือดครึ่งหนึ่ง",
       "Store the damage you take, then convert half of it back to health.",
       "储存所受伤害，将其中一半转回生命。"),
    sk("ultimate", "fusion", "กอดอุ่นๆ", "Warm Hug", "温暖拥抱",
       "ฟื้นเลือด 35% และล้างผลติดลบทั้งหมด",
       "Heal 35% and clear every negative effect.",
       "恢复 35% 生命并清除所有负面效果。") ] },

  /* ── GHOSTS ── they win by not being hit */
  phantom: { cls: "ghost", skills: [
    sk("passive", "eye", "ผิวเลียนแบบ", "Mimetic Skin", "拟态外壳",
       "มีโอกาส 20% หลบดาเมจทั้งหมด",
       "A 20% chance to avoid any hit entirely.",
       "20% 几率完全闪避任何伤害。"),
    sk("active", "trail", "เปลี่ยนรูปหลบ", "Mimic Dodge", "拟态闪避",
       "ข้อถัดไป ตอบผิดก็ไม่เสียเลือด",
       "The next question costs nothing if you get it wrong.",
       "下一题答错不掉血。"),
    sk("ultimate", "orb", "หล่อขึ้นรูปใหม่", "Liquid Reform", "液态重塑",
       "ฟื้นเลือด 25% และล้างผลติดลบทั้งหมด",
       "Reform: heal 25% and clear every negative effect.",
       "重塑：恢复 25% 生命并清除负面效果。") ] },
  specter: { cls: "ghost", skills: [
    sk("passive", "eye", "กลมกลืน", "Blend In", "融入",
       "คู่ต่อสู้มองไม่เห็นเลือดจริงของคุณ",
       "Your real health is hidden from your opponent.",
       "对手无法看到你的真实血量。"),
    sk("active", "chip", "แฝงตัวเข้าใกล้", "Infiltrate", "潜入",
       "ขโมยซิงค์ของคู่ต่อสู้ 30%",
       "Steal 30% of your opponent's sync.",
       "窃取对手 30% 的同步值。"),
    sk("ultimate", "trail", "โปรโตคอลไร้ตัวตน", "Ghost Protocol", "幽灵协议",
       "2 ข้อถัดไป ไม่รับดาเมจเลย",
       "Take no damage at all for two questions.",
       "两题内完全不受伤害。") ] },
  pebble: { cls: "ghost", skills: [
    sk("passive", "gyro", "กลิ้งหลบ", "Roll Away", "滚动闪避",
       "ตอบผิดครั้งแรกของทุกยกไม่เสียเลือด",
       "The first mistake of every round is free.",
       "每回合第一次答错不掉血。"),
    sk("active", "boomerang", "เด้งเปลี่ยนข้อ", "Bounce", "弹跳换题",
       "เปลี่ยนคำถามข้อปัจจุบันเป็นข้อใหม่",
       "Swap the current question for a different one.",
       "将当前题目换成另一题。"),
    sk("ultimate", "thruster", "เร่งสุดแรง", "Full Tilt", "全速",
       "4 ข้อถัดไป ความเร็วเป็นสองเท่า",
       "Double speed for four questions.",
       "接下来四题速度翻倍。") ] },

  /* ── TACTICIANS ── they win by knowing first */
  scout: { cls: "tactician", skills: [
    sk("passive", "scope", "อ่านเกมล่วงหน้า", "Preconstruct", "预演推算",
       "เห็นหมวดของคำถามข้อถัดไปก่อนเสมอ",
       "You always see what the next question is about before it arrives.",
       "总能提前看到下一题的类别。"),
    sk("active", "chip", "วิเคราะห์", "Analyse", "分析",
       "ตัดตัวเลือกที่ผิดออก 2 ข้อ",
       "Strike two wrong options off the current question.",
       "从当前题目中划去两个错误选项。"),
    sk("ultimate", "gyro", "จำลองย้อนเวลา", "Reconstruction", "情景重建",
       "ย้อนคำตอบผิดล่าสุดของคุณ แล้วตอบใหม่",
       "Rewind your last wrong answer and take it again.",
       "回溯你最近一次答错，并重新作答。") ] },
  sentry: { cls: "tactician", skills: [
    sk("passive", "battery", "ของมาตรฐานกองทัพ", "Standard Issue", "标准配给",
       "ทักษะทุกอย่างของคุณคูลดาวน์เร็วขึ้น 20%",
       "All your skills come back 20% sooner.",
       "所有技能冷却缩短 20%。"),
    sk("active", "blaster", "สั่งยิงพร้อมกัน", "Volley Order", "齐射指令",
       "ยิงชุด 3 นัด นัดละไม่มาก แต่ทะลุโล่ทุกนัด",
       "Three small shots — every one of them ignores shields.",
       "三次小额射击，全部无视护盾。"),
    sk("ultimate", "drone", "เรียกกำลังเสริม", "Reinforcements", "增援",
       "2 ข้อถัดไป ตอบถูกทำดาเมจสองเท่า",
       "Right answers deal double damage for two questions.",
       "接下来两题答对造成双倍伤害。") ] },
  pixel: { cls: "tactician", skills: [
    sk("passive", "chip", "แม่นทุกพิกเซล", "Pixel Perfect", "像素级精准",
       "คำถามอ่านโน้ต ตอบถูกทำดาเมจ +25%",
       "Note-reading questions hit 25% harder when you get them right.",
       "读谱题答对伤害 +25%。"),
    sk("active", "pad", "ลวงหน้าจอ", "Screen Feint", "屏幕虚招",
       "ซ่อนคำตอบของคุณจากคู่ต่อสู้ 2 ข้อ",
       "Hide your answers from your opponent for two questions.",
       "两题内对手看不到你的作答。"),
    sk("ultimate", "burst", "กลิตช์", "Glitch", "故障",
       "สลับตำแหน่งตัวเลือกของคู่ต่อสู้ 3 ข้อ",
       "Scramble your opponent's answer buttons for three questions.",
       "三题内打乱对手的选项顺序。") ] },

  /* ── ENGINEERS ── they win by lasting */
  pip: { cls: "engineer", skills: [
    sk("passive", "scope", "สแกนวินิจฉัย", "Diagnostics", "诊断扫描",
       "เห็นว่าคู่ต่อสู้อ่อนหมวดไหนที่สุด",
       "You can see which category your opponent is weakest in.",
       "可以看到对手最弱的题型。"),
    sk("active", "wrench", "ซ่อมกลางสนาม", "Field Repair", "战地维修",
       "ฟื้นเลือด 20%",
       "Patch yourself up for 20% health.",
       "恢复 20% 生命。"),
    sk("ultimate", "coil", "โอเวอร์คล็อก", "Overclock", "超频",
       "3 ข้อถัดไป เวลาตอบ +50% และซิงค์ ×2",
       "Three questions with 50% more time and double sync.",
       "接下来三题作答时间 +50%，同步值翻倍。") ] },
  nova: { cls: "engineer", skills: [
    sk("passive", "battery", "หนุนพลังตั้งต้น", "Assist Boost", "初始助推",
       "เริ่มทุกยกด้วยซิงค์ +3",
       "Every round starts you 3 sync ahead.",
       "每回合开局同步值 +3。"),
    sk("active", "plug", "ชาร์จใหม่", "Recharge", "再充能",
       "ลดคูลดาวน์ทักษะทั้งหมดของคุณลงหนึ่งตา",
       "Take a turn off every one of your cooldowns.",
       "所有技能冷却减少一回合。"),
    sk("ultimate", "fusion", "ซูเปอร์โนวา", "Supernova", "超新星",
       "เปลี่ยนซิงค์ที่สะสมทั้งหมดเป็นดาเมจ แล้วฟื้นเลือดครึ่งหนึ่งของนั้น",
       "Spend all stored sync as damage, then heal for half of it.",
       "将全部同步值转为伤害，并回复其一半为生命。") ] },

  /* ── HERALDS ── they win by changing the terms */
  envoy: { cls: "herald", skills: [
    sk("passive", "chip", "หกล้านรูปแบบภาษา", "Six Million Forms", "百万语系",
       "คำถามที่มีศัพท์ดนตรีต่างประเทศ ได้ซิงค์สองเท่า",
       "Questions using foreign musical terms give double sync.",
       "含外语音乐术语的题目获得双倍同步值。"),
    sk("active", "speaker", "แปลให้", "Translate", "翻译",
       "เปิดเผยตัวเลือกที่ผิดหนึ่งข้อ",
       "Reveal one wrong option.",
       "揭示一个错误选项。"),
    sk("ultimate", "barrier", "เอกสิทธิ์ทางการทูต", "Diplomatic Immunity", "外交豁免",
       "ยกเลิกไม้ตายของคู่ต่อสู้หนึ่งครั้ง",
       "Cancel your opponent's ultimate, once.",
       "取消对手的终极技能一次。") ] },
  keeper: { cls: "herald", skills: [
    sk("passive", "shield", "ปกป้องคนข้างหลัง", "Shelter", "庇护",
       "ตอบผิดข้อแรกของแต่ละหมวดไม่เสียเลือด",
       "The first mistake in each category costs you nothing.",
       "每个题型第一次答错不掉血。"),
    sk("active", "vent", "มือนิ่ง", "Steady Hand", "稳定之手",
       "เพิ่มเวลาตอบให้ตัวเอง 5 วินาที",
       "Five more seconds on your own clock.",
       "自己的作答时间 +5 秒。"),
    sk("ultimate", "halo", "เพลงกล่อม", "Lullaby", "摇篮曲",
       "คู่ต่อสู้เหลือเวลาตอบเพียง 70% เป็นเวลา 3 ข้อ",
       "Your opponent gets only 70% of the clock for three questions.",
       "三题内对手只有 70% 的作答时间。") ] },
  meridian: { cls: "herald", skills: [
    sk("passive", "eye", "เข้าอกเข้าใจ", "Empathy", "共情",
       "เมื่อเลือดต่ำกว่า 30% ซิงค์ที่ได้เป็นสองเท่า",
       "Below 30% health you gain sync twice as fast.",
       "血量低于 30% 时同步值获取翻倍。"),
    sk("active", "coil", "ปลุกให้ตื่นรู้", "Awaken", "觉醒",
       "ดาเมจครั้งถัดไปคิดตามซิงค์ที่สะสมไว้",
       "Your next hit scales with the sync you have banked.",
       "下一次伤害按已累积的同步值计算。"),
    sk("ultimate", "burst", "การลุกขึ้น", "Uprising", "起义",
       "เปลี่ยนซิงค์ทั้งหมดเป็นดาเมจทันที",
       "Convert all sync into damage at once.",
       "立即将全部同步值转化为伤害。") ] },

  /* ── VIRTUOSI ── they win by playing better */
  halcyon: { cls: "virtuoso", skills: [
    sk("passive", "halo", "เสียงประสานสงบ", "Calm Chorus", "宁静和声",
       "ซิงค์ไม่รีเซ็ตเมื่อคุณตอบผิด",
       "A wrong answer no longer resets your sync.",
       "答错不会重置你的同步值。"),
    sk("active", "keytar", "ประสานเสียง", "Harmony", "和声",
       "ตอบถูกคำถามคอร์ดหรือสเกล ฟื้นเลือด 8%",
       "Answer a chord or scale question right and heal 8%.",
       "答对和弦或音阶题恢复 8% 生命。"),
    sk("ultimate", "burst", "เคเดนซ์ปิดท้าย", "Grand Cadence", "终止式",
       "ปิดยกด้วยดาเมจที่คิดจากซิงค์สะสมทั้งหมด",
       "Close the round with damage drawn from all your banked sync.",
       "以全部同步值结算伤害收尾。") ] },
  aurora: { cls: "virtuoso", skills: [
    sk("passive", "halo", "ออร่าบนเวที", "Stage Presence", "舞台气场",
       "ตอบถูกติดกันสะสมแสง — ทุก 3 ครั้ง ดาเมจ +15%",
       "Every third right answer in a row adds 15% damage.",
       "每连续答对三题伤害 +15%。"),
    sk("active", "speaker", "ท่อนฮุกซ้ำ", "Encore Hook", "安可副歌",
       "ใช้ผลของทักษะล่าสุดของคุณซ้ำอีกครั้ง",
       "Repeat the effect of the last skill you used.",
       "重复你上一个使用的技能效果。"),
    sk("ultimate", "burst", "ออโรร่าฟินาเล่", "Aurora Finale", "极光终章",
       "ดาเมจใหญ่ครั้งเดียว และฟื้นเลือด 15%",
       "One large hit, and 15% health back.",
       "一次大型伤害，并回复 15% 生命。") ] },

  /* ══ the soft intake ══════════════════════════════════════════════════════
     Ten chassis built to be held rather than feared. The MECHANICS live on
     the class, not here — CLASS_FX is what the arena reads — so what these
     kits carry is the character: what this particular machine thinks it is
     doing when it does the thing its class does. */
  pudding: { cls: "herald", skills: [
    sk("passive", "vent", "เนื้อนุ่มรับแรง", "Give, Don't Break", "以柔化力",
       "ตัวนิ่มดูดซับแรง รับดาเมจน้อยลงเรื่อยๆ ยิ่งโดนติดกัน",
       "A body that gives instead of resisting takes less from each hit in a row.",
       "以柔化力：连续挨打时，每一下受伤都更少。"),
    sk("active", "speaker", "คลื่นสั่นสะเทือน", "Wobble Pulse", "颤动脉冲",
       "สั่นทั้งตัวจนคลื่นแผ่ออกไป กวนจังหวะของคู่ต่อสู้",
       "Shakes from the inside out until the ripple puts the opponent off their timing.",
       "由内而外的震颤，打乱对手的节奏。"),
    sk("ultimate", "burst", "ละลายแล้วก่อตัวใหม่", "Reset The Set", "重新凝固",
       "ละลายลงกองแล้วก่อตัวใหม่ทั้งหมด — เริ่มยกใหม่เหมือนไม่เคยเจ็บ",
       "Collapses into a puddle and sets again, as if the round had not happened yet.",
       "化作一滩再重新凝固 —— 仿佛这一回合从未开始。") ] },
  acorn: { cls: "engineer", skills: [
    sk("passive", "plate", "เปลือกแข็งขึ้นทุกที", "Harden By Layers", "层层硬化",
       "เปลือกหนาขึ้นทุกครั้งที่ตอบถูก",
       "The shell thickens by one layer with every right answer.",
       "每答对一次，外壳就多硬一层。"),
    sk("active", "wrench", "ปิดฝาเปลือก", "Shell Up", "闭壳",
       "ดึงตัวเข้าใต้ฝา — สิ่งที่ตามมาทันทีไม่โดน",
       "Pulls in under the cap. Whatever lands next does not land.",
       "缩进壳盖之下 —— 紧接着的一击落空。"),
    sk("ultimate", "orb", "หว่านเมล็ด", "Seed The Field", "播种",
       "โปรยเมล็ดลงพื้นทั้งสนาม แล้วทุกอย่างงอกขึ้นพร้อมกัน",
       "Scatters seed across the whole floor, then everything comes up at once.",
       "撒种满场，然后同时破土。") ] },
  cocoa: { cls: "bulwark", skills: [
    sk("passive", "shield", "อบอุ่นไว้ก่อน", "Keep Them Warm", "先暖起来",
       "ยืนใกล้ฝ่ายเดียวกันแล้วทั้งคู่รับดาเมจน้อยลง",
       "Standing close to anyone friendly means both of you take less.",
       "站在同伴身边，两个人都少受伤。"),
    sk("active", "limb", "กอดหมี", "Bear Hug", "熊抱",
       "จับไว้ไม่ให้ขยับ แล้วบีบจนกว่าจะยอม",
       "Holds them still and squeezes until they stop arguing about it.",
       "抱住不放，直到对方不再挣扎。"),
    sk("ultimate", "barrier", "ไม่มีใครผ่านไปได้", "Nobody Gets Past", "无人可越",
       "ยืนขวางไว้ทั้งยก — ดาเมจที่ควรเข้าหายไปครึ่งหนึ่ง",
       "Plants itself in the way for the rest of the round. Half of everything stops there.",
       "整回合挡在前面 —— 一半的伤害到此为止。") ] },
  blossom: { cls: "herald", skills: [
    sk("passive", "halo", "บานตามเสียง", "Opens To Sound", "闻声而开",
       "ตอบถูกกลีบบานทีละกลีบ เกจเต็มเร็วขึ้นตามจำนวนกลีบ",
       "A petal opens for every right answer, and the gauge fills faster for each one.",
       "每答对一次开一瓣，开得越多能量涨得越快。"),
    sk("active", "orb", "ละอองเรณู", "Pollen Drift", "花粉飘散",
       "ปล่อยละอองออกไป คู่ต่อสู้เล็งไม่แม่นไปพักหนึ่ง",
       "Lets the pollen go. Nothing aimed through it lands quite right.",
       "放出花粉，穿过它的攻击都会偏。"),
    sk("ultimate", "burst", "บานสะพรั่ง", "Full Bloom", "盛放",
       "บานพร้อมกันทุกกลีบ ฟื้นเลือดและเติมเกจให้เต็ม",
       "Every petal opens at once: health back, and the gauge full again.",
       "所有花瓣同时绽放：回血，并再次充满能量。") ] },
  pengu: { cls: "bulwark", skills: [
    sk("passive", "plate", "ชั้นไขมันกันหนาว", "Built For Cold", "御寒之躯",
       "หนาวไม่ระคาย — ดีบัฟที่ทำให้ช้าลงหมดฤทธิ์เร็วกว่าปกติ",
       "Cold is not a problem here. Anything that slows you wears off faster.",
       "寒冷不成问题 —— 减速类效果消退得更快。"),
    sk("active", "thruster", "ไถลบนน้ำแข็ง", "Belly Slide", "滑行冲刺",
       "ทิ้งตัวลงไถลเข้าใส่ — เร็วกว่าที่ตัวมันควรจะเร็วได้",
       "Drops flat and slides in, considerably faster than it has any right to be.",
       "扑倒滑行冲入 —— 快得不像它该有的速度。"),
    sk("ultimate", "barrier", "กำแพงน้ำแข็ง", "Ice Wall", "冰墙",
       "ยกกำแพงน้ำแข็งขึ้นมา บังทุกอย่างที่มาจากด้านหน้า",
       "Raises a wall of ice. Everything from the front stops at it.",
       "立起冰墙，正面来的全部止步。") ] },
  bubbly: { cls: "tactician", skills: [
    sk("passive", "eye", "มองผ่านกระจก", "Read Through Glass", "透窗而观",
       "โดมช่วยโฟกัส — เห็นท่าของคู่ต่อสู้ก่อนมันออก",
       "The dome focuses more than air: the opponent's move is readable before it starts.",
       "穹顶不只聚气 —— 对手出手之前就已看穿。"),
    sk("active", "barrier", "ปิดผนึกโดม", "Dome Seal", "穹顶封锁",
       "ปิดโดมสนิท ตัดทุกอย่างที่พยายามเข้ามาหนึ่งครั้ง",
       "Seals the dome. One thing that was going to get in does not.",
       "封闭穹顶，挡下一次本要命中的攻击。"),
    sk("ultimate", "orb", "ฟองสุญญากาศ", "Vacuum Bubble", "真空泡",
       "ห่อคู่ต่อสู้ไว้ในฟอง — ในนั้นไม่มีอะไรเดินหน้าได้เลย",
       "Wraps the opponent in a bubble where nothing they do goes anywhere.",
       "把对手裹进泡里，在里面什么都推进不了。") ] },
  poppy: { cls: "engineer", skills: [
    sk("passive", "coil", "เสาไม่เคยหยุดนิ่ง", "Never Quite Still", "从不静止",
       "เสาสั่นตลอด — เกจเดินเองช้าๆ แม้ตอนไม่ได้ทำอะไร",
       "The antenna never settles, so the gauge creeps up even when nothing is happening.",
       "天线从不停摆 —— 就算什么都不做，能量也会慢慢积累。"),
    sk("active", "plug", "สัญญาณกระตุก", "Signal Jolt", "信号震颤",
       "ส่งสัญญาณแรงหนึ่งครั้ง อะไรที่กำลังชาร์จอยู่ก็สะดุด",
       "One hard pulse. Anything mid-charge stops being mid-charge.",
       "一记强脉冲，正在蓄力的动作全部中断。"),
    sk("ultimate", "battery", "ปล่อยหมดหลอด", "Everything At Once", "一次放光",
       "ปล่อยประจุที่เก็บไว้ทั้งหมดในทีเดียว",
       "Dumps every charge it has been quietly saving, all in one go.",
       "把悄悄攒下的电全部一次放光。") ] },
  honey: { cls: "herald", skills: [
    sk("passive", "drone", "รังไม่เคยอยู่คนเดียว", "Never Alone", "蜂群不孤",
       "มีฝูงตามตลอด — ทุกครั้งที่ตี มีตัวเล็กตามไปด้วย",
       "The swarm follows. Every hit brings a few more with it.",
       "蜂群随行 —— 每次出手都有几只跟着。"),
    sk("active", "drone", "เรียกฝูง", "Swarm Call", "蜂群召集",
       "เรียกทั้งรังมารุมพร้อมกัน",
       "Calls the whole hive down at once.",
       "把整个蜂巢一次叫下来。"),
    sk("ultimate", "fusion", "น้ำผึ้งชั้นดี", "Royal Jelly", "蜂王浆",
       "ทั้งทีมฟื้นเลือดและตีแรงขึ้นไปจนจบยก",
       "Everyone heals and everyone hits harder, for the rest of the round.",
       "全员回血、全员增伤，直到本回合结束。") ] },
  snowbun: { cls: "ghost", skills: [
    sk("passive", "trail", "ไม่มีเสียงฝีเท้า", "No Footsteps", "无声之足",
       "เดินบนหิมะไม่ทิ้งรอย — โอกาสหลบสูงขึ้น",
       "Crosses snow without marking it. Harder to hit for the same reason.",
       "踏雪无痕 —— 也因此更难被击中。"),
    sk("active", "thruster", "กระโดดหิมะ", "Powder Hop", "踏雪跃",
       "หายไปหนึ่งจังหวะ แล้วโผล่หลังคู่ต่อสู้",
       "Gone for one beat, and standing behind them for the next.",
       "消失一拍，下一拍已在对手身后。"),
    sk("ultimate", "burst", "พายุหิมะเงียบ", "Silent Whiteout", "无声白幕",
       "หิมะกลบทั้งสนาม — โจมตีทุกครั้งจนจบยกเป็นคริติคอล",
       "The snow closes over everything. Until the round ends, every hit is a critical.",
       "白雪吞没全场 —— 回合结束前每一击都是暴击。") ] },
  plushy: { cls: "bulwark", skills: [
    sk("passive", "plate", "ยัดไส้แน่น", "Stuffed Full", "填得很实",
       "ข้างในเป็นนุ่นล้วน — ดาเมจต่อครั้งถูกตัดเพดานไว้",
       "There is nothing in here but stuffing, so no single hit can take very much.",
       "里面全是棉花 —— 单次伤害有上限。"),
    sk("active", "wrench", "เย็บตะเข็บใหม่", "Reseam", "重新缝合",
       "เย็บรอยขาดกลับ — ฟื้นเลือดและล้างสถานะติดตัว",
       "Sews the tear shut: health back, and whatever was clinging to you gone.",
       "把裂口缝好：回血，并清除身上的负面状态。"),
    sk("ultimate", "barrier", "ตุ๊กตาแทนตัว", "Take My Place", "替身布偶",
       "ทิ้งตุ๊กตาไว้แทน — ครั้งต่อไปที่ควรตาย ไม่ตาย",
       "Leaves a doll where you were standing. The next hit that should finish you does not.",
       "留下布偶替身 —— 下一次致命一击不会致命。") ] },

  /* ══ the hard intake ══════════════════════════════════════════════════════ */
  wraith: { cls: "ghost", skills: [
    sk("passive", "trail", "ไม่มีอะไรให้จับ", "Nothing To Hold", "无处可抓",
       "โครงกลวง — การจับล็อกทุกชนิดหลุดผ่านไป",
       "A hollow frame. Anything that tries to grab it closes on nothing.",
       "中空的骨架 —— 任何擒抱都会落空。"),
    sk("active", "trail", "ผ่านทะลุ", "Pass Through", "穿身而过",
       "เดินผ่านคู่ต่อสู้ตรงๆ แล้วโผล่ด้านหลัง",
       "Walks straight through them and comes out the other side.",
       "径直穿过对手，从背后现身。"),
    sk("ultimate", "cutter", "เสียงจากที่ว่าง", "Voice From Nowhere", "虚空之声",
       "หายไปทั้งยก โจมตีจากมุมที่ไม่มีใครมอง",
       "Gone for the round, hitting from wherever nobody is looking.",
       "整回合消失，从无人注视处出手。") ] },
  magnus: { cls: "bulwark", skills: [
    sk("passive", "plate", "หนักเกินจะขยับ", "Too Heavy To Move", "重不可撼",
       "ไม่ถูกผลักถอย และไม่เสียหลักจากการโดนตี",
       "Cannot be pushed back, and does not stagger.",
       "无法被击退，也不会踉跄。"),
    sk("active", "limb", "ทุบลงพื้น", "Ground Slam", "碎地重击",
       "ทุบพื้นจนสะเทือน ทุกอย่างที่ยืนอยู่เสียหลัก",
       "Hits the floor hard enough that everything standing on it stops standing well.",
       "重击地面，站在上面的一切都失去平衡。"),
    sk("ultimate", "barrier", "กำแพงเคลื่อนที่", "Walking Wall", "行走的墙",
       "เดินหน้าอย่างเดียวจนจบยก อะไรขวางก็พังไป",
       "Only forwards, for the rest of the round. Whatever is in the way stops being in the way.",
       "回合内只进不退，挡路的东西不再挡路。") ] },
  saber: { cls: "striker", skills: [
    sk("passive", "sword", "คมอยู่เสมอ", "Always Drawn", "常持锋刃",
       "โจมตีครั้งแรกของทุกยกเป็นคริติคอลเสมอ",
       "The first strike of every round is a critical, without exception.",
       "每回合的第一击必定暴击。"),
    sk("active", "sword", "ชักดาบครั้งเดียว", "One Draw", "居合一闪",
       "ชักออกและเก็บกลับในจังหวะเดียว ผู้ที่โดนมักไม่ทันเห็น",
       "Drawn and sheathed in the same motion. Most of what it hits never saw it.",
       "拔刀与收刀只在一瞬，中招者多半没看见。"),
    sk("ultimate", "cutter", "แปดวิถีดาบ", "Eight Cuts", "八连斩",
       "แปดครั้งในจังหวะเดียว นับเป็นคอมโบเดียว",
       "Eight strikes in the time of one, and they all count as the same combo.",
       "一拍之内八斩，全部计为同一段连击。") ] },
  oracle: { cls: "tactician", skills: [
    sk("passive", "scope", "เจ็ดตาไม่กระพริบ", "Seven Unblinking", "七目不瞬",
       "เห็นคำถามล่วงหน้าเสมอหนึ่งข้อ",
       "Always one question further ahead than the fight is.",
       "永远比战局早看一题。"),
    sk("active", "eye", "อ่านอนาคต", "Read Ahead", "预读",
       "ตัดตัวเลือกที่ผิดออกไปก่อนคำถามจะมาถึง",
       "Strikes the wrong answers off before the question has even arrived.",
       "在问题到来之前就划掉错误选项。"),
    sk("ultimate", "orb", "เห็นทั้งเส้นเวลา", "The Whole Line", "洞见全线",
       "รู้ทุกคำตอบที่เหลือของยกนี้",
       "Knows every answer left in this round.",
       "知晓本回合剩下的所有答案。") ] },
  korax: { cls: "ghost", skills: [
    sk("passive", "eye", "จำหน้าได้", "Remembers Faces", "记得面孔",
       "ยิ่งสู้กับคนเดิมนานยิ่งแม่น — ดาเมจไต่ขึ้นทั้งแมตช์",
       "The longer it fights the same opponent, the better it gets at it.",
       "对同一个对手打得越久，越准。"),
    sk("active", "beam", "โฉบลงจากมืด", "Dark Stoop", "暗袭俯冲",
       "ทิ้งดิ่งลงมาจากมุมบน คู่ต่อสู้ไม่มีจังหวะตั้งรับ",
       "Drops out of the top of the frame with nothing in between to react to.",
       "自上方俯冲而下，对手来不及架起防御。"),
    sk("ultimate", "burst", "ฝูงกาบดบัง", "Unkindness", "鸦群蔽日",
       "ฝูงกาบดบังทั้งสนาม โจมตีจากทุกทิศพร้อมกัน",
       "The flock blots out the arena and comes in from every side at once.",
       "鸦群遮蔽全场，从四面八方同时扑下。") ] },
  tempest: { cls: "striker", skills: [
    sk("passive", "thruster", "ไม่เคยหยุดนิ่ง", "Never Settles", "从不停歇",
       "ยิ่งเคลื่อนที่ต่อเนื่องยิ่งแรง — ดาเมจไต่ขึ้นตามระยะที่วิ่ง",
       "Damage rises with distance covered. Standing still is the only way to lose it.",
       "移动越久伤害越高 —— 站着不动就会归零。"),
    sk("active", "thruster", "พุ่งทะลวง", "Overrun", "突进",
       "พุ่งผ่านทะลุ ชนทุกอย่างที่ขวางระหว่างทาง",
       "Straight through, hitting everything between here and there.",
       "一路直穿，撞开途中的一切。"),
    sk("ultimate", "gyro", "ตาพายุ", "Eye Of It", "风暴之眼",
       "ยืนนิ่งกลางพายุที่ตัวเองสร้าง ทุกอย่างรอบตัวโดนไปเรื่อยๆ",
       "Stands still in the middle of a storm of its own making, and everything around it keeps taking it.",
       "静立于自己掀起的风暴中心，周遭持续受创。") ] },
  bastion: { cls: "bulwark", skills: [
    sk("passive", "plate", "ช่องเดียวเท่านั้น", "One Opening", "只有一孔",
       "มีช่องเดียวทั้งตัว — ดาเมจจากด้านหน้าลดลงมาก",
       "There is exactly one opening in it, and it is not facing you.",
       "全身只有一个开口 —— 正面伤害大幅削减。"),
    sk("active", "barrier", "ปิดช่องยิง", "Close The Slit", "闭合射孔",
       "ปิดช่องสุดท้าย — ยกนี้ไม่มีอะไรเข้าได้",
       "Shuts the last opening. Nothing gets in this round.",
       "关上最后一个孔 —— 本回合无物可入。"),
    sk("ultimate", "grenade", "เปิดช่องทั้งหมด", "All Ports Open", "全孔开放",
       "เปิดทุกช่องพร้อมกันแล้วยิงออกทุกทิศ",
       "Opens every port at once and fires out of all of them.",
       "所有射孔同时开启，向四面开火。") ] },
  nyx: { cls: "ghost", skills: [
    sk("passive", "halo", "แข็งแรงขึ้นในความมืด", "Stronger In The Dark", "暗中更强",
       "ยิ่งเลือดน้อยยิ่งเร็ว — ความเร็วไต่ขึ้นเมื่อเจ็บ",
       "The lower the health, the faster it moves.",
       "血量越低，动作越快。"),
    sk("active", "cutter", "จันทร์เสี้ยว", "Crescent Cut", "弦月斩",
       "โค้งเดียวจากมุมมืด ผ่านการ์ดไปเลย",
       "One arc out of the dark, and the guard is not part of the conversation.",
       "自暗处一道弧光，格挡形同虚设。"),
    sk("ultimate", "burst", "จันทร์ดับ", "New Moon", "朔月",
       "ดับไฟทั้งสนาม — ในความมืดไม่มีใครกันได้",
       "Puts the arena out. In the dark, nobody blocks anything.",
       "熄灭全场光线 —— 黑暗中无人能挡。") ] },
  forge: { cls: "engineer", skills: [
    sk("passive", "vent", "ยิ่งร้อนยิ่งแรง", "Runs Hot", "越热越强",
       "ความร้อนสะสมทั้งยก และดาเมจขึ้นตามมัน",
       "Heat builds across the round, and damage builds with it.",
       "热度整回合累积，伤害随之上升。"),
    sk("active", "grenade", "เปิดเตา", "Open The Furnace", "开炉",
       "เปิดฝาเตาออก ทุกอย่างที่อยู่ข้างหน้าโดนความร้อนเต็มๆ",
       "Opens the furnace door. Everything in front of it gets the inside of a foundry.",
       "打开炉门，正面的一切承受整座熔炉。"),
    sk("ultimate", "fusion", "หลอมใหม่ทั้งตัว", "Recast", "重铸",
       "หลอมตัวเองใหม่กลางยก — ซ่อมทุกอย่างและออกมาแข็งกว่าเดิม",
       "Recasts itself mid-round: everything repaired, and harder than it was.",
       "回合中重铸自身：全部修复，且比之前更硬。") ] },
  zenith: { cls: "herald", skills: [
    sk("passive", "halo", "วงแหวนไม่เคยดับ", "The Ring Holds", "圣环不灭",
       "เกจเต็มเร็วขึ้น และไม่ลดลงเมื่อตอบผิด",
       "The gauge fills faster, and a wrong answer does not take any of it away.",
       "能量充得更快，且答错不会流失。"),
    sk("active", "speaker", "วงแหวนศักดิ์สิทธิ์", "Halo Chord", "圣环和弦",
       "วงแหวนสั่นเป็นคอร์ด ฟื้นเลือดตามจำนวนข้อที่ตอบถูกในยกนี้",
       "The ring rings. Health comes back in proportion to what you got right this round.",
       "圣环鸣响，按本回合答对的题数回血。"),
    sk("ultimate", "fusion", "จุดสูงสุด", "Zenith", "天顶",
       "วงแหวนสว่างจนทั้งสนามหยุด แล้วทุกอย่างที่ค้างไว้ลงพร้อมกัน",
       "The ring goes bright enough to stop the arena, and everything held back lands at once.",
       "圣环大放光明使全场静止，所有蓄势一次落下。") ] },
};

/* the class a chassis belongs to, for anything that just needs the label */
export function classOf(model) {
  const e = MODEL_SKILLS[model];
  return (e && MODEL_CLASS[e.cls]) || MODEL_CLASS.striker;
}
// the class KEY, for anything that needs to branch on the class rather than
// display it — the avatar picks its shoulder crest off this
export function classKeyOf(model) {
  const e = MODEL_SKILLS[model];
  return (e && MODEL_CLASS[e.cls]) ? e.cls : "striker";
}
export function skillsOf(model) {
  const e = MODEL_SKILLS[model];
  return (e && e.skills) || [];
}
