/* ── tigamodel/knowledge/university-sources.js ──
   Source registry for university-sourced music knowledge (spec §10-§12).

   Collection method (owner directive 2026-09-17): gather music knowledge
   attributed to leading music universities/conservatories of each country,
   from public internet pages. Every source below was ACTUALLY READ on
   2026-09-17 via its URL (institution site or its Wikipedia article).
   Nothing is invented; if a fact is not backed by a page we could open,
   it is NOT in this file. Content written from these sources is
   PARAPHRASED pedagogical facts (not copied text), each carrying its
   source_id so every KB entry stays traceable (no fake citations — §12).

   License stance: facts about curricula/traditions are ideas/facts (not
   copyrightable expression); paraphrased in our own words; source metadata
   recorded for provenance. No proprietary course materials are reproduced. ── */

export const SOURCES = {
  "mahidol-music-wiki": {
    title: "College of Music, Mahidol University — overview and history",
    url: "https://en.wikipedia.org/wiki/College_of_Music,_Mahidol_University",
    site: "en.wikipedia.org",
    institution: "College of Music, Mahidol University (Thailand)",
    country: "TH",
    institution_url: "http://www.music.mahidol.ac.th",
    read_at: "2026-09-17",
    reliability: "high", // tertiary source with cited facts about the institution
    notes: "First comprehensive music school in Thailand (est. 1994); teaching continuum from age 3 through Ph.D.; large general-public music campus.",
  },
  "berklee-wiki": {
    title: "Berklee College of Music — history and contemporary-music focus",
    url: "https://en.wikipedia.org/wiki/Berklee_College_of_Music",
    site: "en.wikipedia.org",
    institution: "Berklee College of Music (USA)",
    country: "US",
    institution_url: "https://berklee.edu",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Largest independent contemporary-music college; founded around the Schillinger System of harmony and composition; practitioner-taught model; jazz/contemporary emphasis.",
  },
  "berklee-home": {
    title: "Berklee College of Music — official site (areas of study)",
    url: "https://www.berklee.edu/",
    site: "berklee.edu",
    institution: "Berklee College of Music (USA)",
    country: "US",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Official study areas include Music Theory, Ear Training, Harmony as a distinct discipline cluster; Piano as a dedicated performance area.",
  },
  "juilliard-wiki": {
    title: "The Juilliard School — history and structure",
    url: "https://en.wikipedia.org/wiki/Juilliard_School",
    site: "en.wikipedia.org",
    institution: "The Juilliard School (USA)",
    country: "US",
    institution_url: "https://www.juilliard.edu",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Founded 1905 as Institute of Musical Art; music division largest/oldest; pre-college through doctorate training continuum.",
  },
  "moscow-conservatory-wiki": {
    title: "Moscow State Tchaikovsky Conservatory — history",
    url: "https://en.wikipedia.org/wiki/Moscow_Conservatory",
    site: "en.wikipedia.org",
    institution: "Moscow State Tchaikovsky Conservatory (Russia)",
    country: "RU",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Founded 1866 by Nikolai Rubinstein; Tchaikovsky appointed professor of theory and harmony at opening; piano class taught from the earliest years.",
  },
  "paris-conservatory-wiki": {
    title: "Conservatoire de Paris — history and 'French School' tradition",
    url: "https://en.wikipedia.org/wiki/Conservatoire_de_Paris",
    site: "en.wikipedia.org",
    institution: "Conservatoire de Paris / CNSMDP (France)",
    country: "FR",
    institution_url: "https://www.conservatoiredeparis.fr",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Founded 1795; draws on the 'French School' tradition; historic piano faculty include Louise Farrenc, Henri Herz, Antoine François Marmontel.",
  },
  "ccom-wiki": {
    title: "Central Conservatory of Music — programs and scale",
    url: "https://en.wikipedia.org/wiki/Central_Conservatory_of_Music",
    site: "en.wikipedia.org",
    institution: "Central Conservatory of Music (China)",
    country: "CN",
    institution_url: "http://www.ccom.edu.cn",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "National music academy of China (est. 1950); piano among core undergraduate programs; complete ladder from primary schools through doctorate; owns 500+ pianos.",
  },
  "tokyo-geidai-wiki": {
    title: "Tokyo University of the Arts — music faculty history",
    url: "https://en.wikipedia.org/wiki/Tokyo_University_of_the_Arts",
    site: "en.wikipedia.org",
    institution: "Tokyo University of the Arts / Geidai (Japan)",
    country: "JP",
    institution_url: "https://www.geidai.ac.jp/english/",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Music education lineage from Tokyo Music School (1887); national arts university integrating fine arts and music; exchanges with European conservatories.",
  },
  "karts-wiki": {
    title: "Korea National University of Arts (K-Arts) — School of Music",
    url: "https://en.wikipedia.org/wiki/Korea_National_University_of_Arts",
    site: "en.wikipedia.org",
    institution: "Korea National University of Arts (South Korea)",
    country: "KR",
    institution_url: "http://www.karts.ac.kr/",
    read_at: "2026-09-17",
    reliability: "medium-high",
    notes: "National arts university (est. 1993) with a dedicated School of Music among its six schools; conservatory-style training model.",
  },
  "rcm-home": {
    title: "Royal College of Music — official site (programmes, Centre for Performance Science)",
    url: "https://www.rcm.ac.uk/",
    site: "rcm.ac.uk",
    institution: "Royal College of Music (UK)",
    country: "UK",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "London conservatoire (est. 1882); intensive public-performance programme ethos; Centre for Performance Science research (performance psychology/science).",
  },
  /* ── Global music-THEORY references (owner directive 2026-09-17: gather
     theory knowledge from around the world so the model teaches theory and
     practice both well). These are the standard reference articles on the
     specific theory topics, all read 2026-09-17. ── */
  "theory-overview-wiki": {
    title: "Music theory — definition, scope, and the world's theoretical traditions",
    url: "https://en.wikipedia.org/wiki/Music_theory",
    site: "en.wikipedia.org",
    institution: "Music theory (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Three uses of the term (rudiments / scholarly study / general principles); Mesopotamian interval tablets pre-1500 BCE; Chinese theory from numbers 12-5-8; theory exists in all musical cultures.",
  },
  "harmony-wiki": {
    title: "Harmony — vertical and horizontal dimensions, consonance/dissonance, resolution",
    url: "https://en.wikipedia.org/wiki/Harmony",
    site: "en.wikipedia.org",
    institution: "Harmony (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Harmony = combining pitches into chords and chords into progressions; vertical (frequency-space) + horizontal (time-space); consonance/dissonance balance; tensions; Aristoxenus: the listener's ear decides.",
  },
  "chord-wiki": {
    title: "Chord — triads, sevenths, arpeggios, progressions, figured bass",
    url: "https://en.wikipedia.org/wiki/Chord_(music)",
    site: "en.wikipedia.org",
    institution: "Chord (music) (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Triad = most common chord; arpeggio = notes sounded separately; dominant seventh became the fixture of the common practice period; chord notation systems (figured bass, Roman numerals, Nashville numbers).",
  },
  "cadence-wiki": {
    title: "Cadence — the four main types and their chord progressions",
    url: "https://en.wikipedia.org/wiki/Cadence",
    site: "en.wikipedia.org",
    institution: "Cadence (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Authentic V-I, half x-V, plagal IV-I, deceptive V-vi; US vs British naming (authentic/perfect, deceptive/interrupted); cadences are strong tonic indicators — Lowinsky: 'the cradle of tonality'.",
  },
  "harmonic-function-wiki": {
    title: "Harmonic function — Tonic/Subdominant/Dominant and the two theories",
    url: "https://en.wikipedia.org/wiki/Function_(music)",
    site: "en.wikipedia.org",
    institution: "Function (music) (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Riemann's German function theory (T/S/D letters) vs the Viennese Roman-numeral theory (Sechter, Schoenberg, Schenker); both descend from Rameau 1722; the three primary triads F-C-G produce the major scale.",
  },
  "circle-of-fifths-wiki": {
    title: "Circle of fifths — key layout, closely related keys, modulation",
    url: "https://en.wikipedia.org/wiki/Circle_of_fifths",
    site: "en.wikipedia.org",
    institution: "Circle of fifths (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Twelve pitch classes in ascending perfect fifths; adjacent keys = closely related signatures; harmonic progressions commonly move between adjacent keys; Pythagorean comma → equal temperament.",
  },
  "metre-wiki": {
    title: "Metre (music) — pulse hierarchy, accent patterns, time signatures",
    url: "https://en.wikipedia.org/wiki/Meter_(music)",
    site: "en.wikipedia.org",
    institution: "Metre (music) (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Metre = recurring accent pattern over the pulse; beats exist only once some pulses are accented; listeners hold a metric hierarchy on minimal evidence; duple/triple subdivision; world systems (tala etc.).",
  },
  "rhythm-wiki": {
    title: "Rhythm — strong/weak element grouping, distinguished from pulse and metre",
    url: "https://en.wikipedia.org/wiki/Rhythm",
    site: "en.wikipedia.org",
    institution: "Rhythm (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Rhythm = grouping of unaccented beats around an accented one; distinct from pulse (the steady stream) and metre (the accent framework); timing of sounds and silences on a human scale.",
  },
  "solfege-wiki": {
    title: "Solfège — Guido of Arezzo, fixed vs movable do, solmization worldwide",
    url: "https://en.wikipedia.org/wiki/Solf%C3%A8ge",
    site: "en.wikipedia.org",
    institution: "Solfège (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "From Guido of Arezzo's 11th-c. hymn syllables ut-re-mi-fa-sol-la; fixed do (syllable = pitch) vs movable do (syllable = degree); a mnemonic for audiating pitch — the international ear-training tool.",
  },
  "sight-reading-wiki": {
    title: "Sight-reading — eye-hand span, working memory, audiation link",
    url: "https://en.wikipedia.org/wiki/Sight-reading",
    site: "en.wikipedia.org",
    institution: "Sight-reading (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Reading + performing unseen notation; skilled readers look further ahead (eye-hand span) storing notes in working memory; depends on short-term musical memory; silent sight-reading = audiation.",
  },
  "improvisation-wiki": {
    title: "Musical improvisation — history and harmonic frameworks",
    url: "https://en.wikipedia.org/wiki/Musical_improvisation",
    site: "en.wikipedia.org",
    institution: "Musical improvisation (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Improvisation over a chord framework was central from Bach to Chopin (cadenza, prelude, figured-bass realisation, ornamentation); raga = the improvisational framework in Indian classical music.",
  },

  /* ── Global teaching methods + practice science (owner directive: the model
     must teach well, not just know theory). All read 2026-09-17. ── */
  "suzuki-wiki": {
    title: "Suzuki method — mother-tongue approach, environment, review",
    url: "https://en.wikipedia.org/wiki/Suzuki_method",
    site: "en.wikipedia.org",
    institution: "Suzuki method (Shinichi Suzuki, Japan)",
    country: "JP",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Talent Education: ability is made by environment, not inborn; learn by ear before reading (children speak before they read); daily listening; memorisation; constant review of every piece; small steps, scaled to the child; no aptitude gate.",
  },
  "koday-wiki": {
    title: "Kodály method — sing first, child-developmental sequencing, solfège",
    url: "https://en.wikipedia.org/wiki/Kod%C3%A1ly_method",
    site: "en.wikipedia.org",
    institution: "Kodály method (Zoltán Kodály, Hungary)",
    country: "HU",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Voice is the first instrument — sing before play; experience (listen/sing/move) before notation; rhythm syllables (ta, ti-ti); easiest-concept-first sequencing; constant review through games; UNESCO intangible heritage 2016.",
  },
  "orff-wiki": {
    title: "Orff Schulwerk — elemental music, learning by doing, play-based",
    url: "https://en.wikipedia.org/wiki/Orff_Schulwerk",
    site: "en.wikipedia.org",
    institution: "Orff Schulwerk (Carl Orff & Gunild Keetman, Germany)",
    country: "DE",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Elemental music close to a child's world of play; every concept learned by DOING; break each activity into its simplest form and present one step at a time; improvisation and ostinato as core materials; no pressure of being judged.",
  },
  "dalcroze-wiki": {
    title: "Dalcroze eurhythmics — rhythm through the body, movement before notation",
    url: "https://en.wikipedia.org/wiki/Dalcroze_eurhythmics",
    site: "en.wikipedia.org",
    institution: "Dalcroze eurhythmics (Émile Jaques-Dalcroze, Switzerland)",
    country: "CH",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Rhythm lives in the body: experience a concept through movement before its visual symbol; kinesthetic foundation for steady beat; influenced Kodály/Orff/Suzuki; improvisation as one of the three lesson pillars.",
  },
  "gordon-wiki": {
    title: "Gordon Music Learning Theory — audiation and learning sequences",
    url: "https://en.wikipedia.org/wiki/Gordon_Music_Learning_Theory",
    site: "en.wikipedia.org",
    institution: "Gordon music learning theory (Edwin Gordon, US)",
    country: "US",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Audiation = hearing and comprehending music that is not physically present ('audiation is to music what thought is to language'); discrimination → inference learning ladder: aural/oral → verbal association → symbolic; pattern vocabulary over isolated notes.",
  },
  "piano-pedagogy-wiki": {
    title: "Piano pedagogy — the field, teacher factors, lineage (Taubman, Neuhaus …)",
    url: "https://en.wikipedia.org/wiki/Piano_pedagogy",
    site: "en.wikipedia.org",
    institution: "Piano pedagogy (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Teaching quality factors: performance competence, repertoire knowledge, adapting to personality/learning style; lineage Czerny → Leschetizky → Neuhaus; Taubman and Whiteside re-imagined technique as coordinated motion, not finger strength.",
  },
  "taubman-wiki": {
    title: "Dorothy Taubman — the Taubman Approach (coordinated motion, injury-free playing)",
    url: "https://en.wikipedia.org/wiki/Dorothy_Taubman",
    site: "en.wikipedia.org",
    institution: "Dorothy Taubman (US)",
    country: "US",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Technique from coordinated motions of the whole arm — forearm rotation, shaping, grouping, in-and-out — not finger force; famous for rehabilitating injured pianists (incl. Leon Fleisher); thumb-under rethought as passing under with rotation.",
  },
  "abrsm-wiki": {
    title: "ABRSM — the world's graded music exam ladder (est. 1889)",
    url: "https://en.wikipedia.org/wiki/ABRSM",
    site: "en.wikipedia.org",
    institution: "ABRSM (UK)",
    country: "UK",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Grades 1-8 + diplomas across 90+ countries, 600k+ candidates a year; graded ladder = the de-facto global scaffold: pieces + technique (scales) + supporting tests (sight-reading, aural) per grade.",
  },
  "trinity-wiki": {
    title: "Trinity College London — graded exams with flexible repertoire choice",
    url: "https://en.wikipedia.org/wiki/Trinity_College_London",
    site: "en.wikipedia.org",
    institution: "Trinity College London (UK)",
    country: "UK",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Grades Initial-8 since 1877; three assessment categories (pieces / technical work / supporting tests incl. improvisation); candidates choose among pieces — flexibility within a scaffold.",
  },
  "rcm-toronto-wiki": {
    title: "The Royal Conservatory of Music — the North American graded system",
    url: "https://en.wikipedia.org/wiki/Royal_Conservatory_of_Music",
    site: "en.wikipedia.org",
    institution: "The Royal Conservatory of Music (Canada)",
    country: "CA",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Est. 1886 Toronto; RCM certificate program grades 1-10 + ARCT used across Canada/US; elementary/intermediate/advanced teacher certification tied to the same ladder.",
  },
  "practice-wiki": {
    title: "Deliberate practice (K. Anders Ericsson) — how one practises beats how long",
    url: "https://en.wikipedia.org/wiki/Practice_(learning_method)",
    site: "en.wikipedia.org",
    institution: "Practice (learning method) — deliberate practice",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Expertise reflects HOW one practises, not repetition count: break the skill into chunks, work on weaknesses at the edge of ability, with immediate feedback; without feedback practice can be ineffective or even detrimental.",
  },
  "spaced-repetition-wiki": {
    title: "Spaced repetition — Ebbinghaus's forgetting curve, expanding intervals",
    url: "https://en.wikipedia.org/wiki/Spaced_repetition",
    site: "en.wikipedia.org",
    institution: "Spaced repetition (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Review at expanding intervals defeats the forgetting curve (Ebbinghaus 1880s); recall success doubles the next interval, failure resets it — the schedule mechanic behind keeping reviewed repertoire alive.",
  },
  "testing-effect-wiki": {
    title: "Testing effect / retrieval practice — recalling beats re-reading",
    url: "https://en.wikipedia.org/wiki/Testing_effect",
    site: "en.wikipedia.org",
    institution: "Testing effect (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Actively retrieving from memory (playing from memory, naming the key, quizzing) produces more durable learning than passive re-exposure; active vs passive repetition distinguished since Bacon 1620, James 1890.",
  },
  "chunking-wiki": {
    title: "Chunking — working-memory limits and meaningful groups",
    url: "https://en.wikipedia.org/wiki/Chunking_(psychology)",
    site: "en.wikipedia.org",
    institution: "Chunking (psychology) (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Working memory holds a handful of items — but a chunk of 2-6 associated items counts as ONE; grouping notes into hands/figures/phrases is what makes long passages learnable at all.",
  },
  "music-education-wiki": {
    title: "Music education — the 20th-century method families, one map",
    url: "https://en.wikipedia.org/wiki/Music_education",
    site: "en.wikipedia.org",
    institution: "Music education (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "The method map in one place: Dalcroze (movement), Kodály (voice), Orff (elemental doing), Suzuki (mother tongue), Gordon (audiation), Carabo-Cone (concrete environment), MMCP (creation), WMP (culture).",
  },
  /* ── Piano-craft + teacher-craft references (owner directive 2026-09-17:
     fill the audited gaps — pedal/dynamics/jazz/intervals for GROUP 1;
     memory/ear/stage-fright/motivation/Thai-music for GROUP 2+3). All read
     2026-09-17, same provenance rules. ── */
  "piano-pedals-wiki": {
    title: "Piano pedals — the three pedals of the modern piano",
    url: "https://en.wikipedia.org/wiki/Piano_pedals",
    site: "en.wikipedia.org",
    institution: "Piano pedals (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Modern pianos have three pedals: sustain (right), soft/una corda (left), sostenuto (middle, rarely used in practice); each has a distinct mechanical action.",
  },
  "sustain-pedal-wiki": {
    title: "Sustain pedal — lifting dampers so strings ring on",
    url: "https://en.wikipedia.org/wiki/Sustain_pedal",
    site: "en.wikipedia.org",
    institution: "Sustain pedal (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "The rightmost pedal lifts the dampers so strings continue sounding after keys are released; core expressive device of the piano.",
  },
  "dynamics-wiki": {
    title: "Dynamics (music) — the p-to-f loudness vocabulary",
    url: "https://en.wikipedia.org/wiki/Dynamics_(music)",
    site: "en.wikipedia.org",
    institution: "Dynamics (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Italian dynamic marks (pp/ppp to ff/fff, mp/mf, crescendo/diminuendo, sforzando) indicate RELATIVE loudness, not fixed volumes; the piano's own name means 'soft-loud'.",
  },
  "jazz-piano-wiki": {
    title: "Jazz piano — comping, voicings, improvisation over changes",
    url: "https://en.wikipedia.org/wiki/Jazz_piano",
    site: "en.wikipedia.org",
    institution: "Jazz piano (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Jazz pianists accompany (comp) with rhythmically placed chord voicings and improvise over chord changes; the technique extends classical harmony into live re-creation.",
  },
  "twelve-bar-blues-wiki": {
    title: "Twelve-bar blues — the I-IV-V form behind jazz and pop",
    url: "https://en.wikipedia.org/wiki/Twelve-bar_blues",
    site: "en.wikipedia.org",
    institution: "Twelve-bar blues (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "12-bar form built on tonic/subdominant/dominant (I-IV-V); blue notes (flattened 3rd/5th/7th) give the genre its sound; foundation of jazz, R&B, rock 'n' roll.",
  },
  "extended-chord-wiki": {
    title: "Extended chord — 9ths, 11ths, 13ths beyond the seventh",
    url: "https://en.wikipedia.org/wiki/Extended_chord",
    site: "en.wikipedia.org",
    institution: "Extended chord (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Harmonies built by stacking thirds past the seventh (9th/11th/13th); used in jazz, R&B, film music; note the app already teaches these in its pathway.",
  },
  "slash-chord-wiki": {
    title: "Slash chord — a chord played over a different bass note",
    url: "https://en.wikipedia.org/wiki/Slash_chord",
    site: "en.wikipedia.org",
    institution: "Slash chord (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Notation 'C/E' = C major chord with E in the bass; used for stepwise basslines and specifying inversions; the bass note after the slash is the sounding bottom note.",
  },
  "interval-wiki": {
    title: "Interval (music) — distance between two pitches",
    url: "https://en.wikipedia.org/wiki/Interval_(music)",
    site: "en.wikipedia.org",
    institution: "Interval (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Intervals are numbered (unison to octave and beyond) and qualified (major/minor/perfect/augmented/diminished); harmonic = sounded together, melodic = sounded in sequence.",
  },
  "mode-wiki": {
    title: "Mode (music) — the seven modes of the major scale",
    url: "https://en.wikipedia.org/wiki/Mode_(music)",
    site: "en.wikipedia.org",
    institution: "Mode (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Ionian, Dorian, Phrygian, Lydian, Mixolydian, Aeolian, Locrian — one set of notes, different tonics, each with a distinct character; modal jazz/rock use them by name.",
  },
  "inversion-wiki": {
    title: "Inversion (music) — which note is in the bass",
    url: "https://en.wikipedia.org/wiki/Inversion_(music)",
    site: "en.wikipedia.org",
    institution: "Inversion (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "A chord's inversion is determined by its lowest note: root position, first inversion (third in bass), second inversion (fifth in bass) for triads; same notes, different stability.",
  },
  "voice-leading-wiki": {
    title: "Voice leading — moving between chords with the smallest motion",
    url: "https://en.wikipedia.org/wiki/Voice_leading",
    site: "en.wikipedia.org",
    institution: "Voice leading (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "The practice of connecting chords so each part moves smoothly (small steps, common tones held); classical common-practice style forbids parallel fifths/octaves; basis of smooth chord changes on piano.",
  },
  "modulation-wiki": {
    title: "Modulation (music) — changing key inside a piece",
    url: "https://en.wikipedia.org/wiki/Modulation_(music)",
    site: "en.wikipedia.org",
    institution: "Modulation (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Keys change via pivot chords shared by both keys, or by direct shift; common destinations are closely related keys (dominant, relative minor).",
  },
  "music-memory-wiki": {
    title: "Music-related memory — visual, auditory, kinesthetic memory in performance",
    url: "https://en.wikipedia.org/wiki/Music-related_memory",
    site: "en.wikipedia.org",
    institution: "Music-related memory (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Performers memorize through multiple channels — visual (score/hand pictures), auditory (inner hearing), kinesthetic (motor patterns) — and strong memorization combines them deliberately.",
  },
  "ear-training-wiki": {
    title: "Ear training — hearing intervals, chords and rhythms by name",
    url: "https://en.wikipedia.org/wiki/Ear_training",
    site: "en.wikipedia.org",
    institution: "Ear training (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "A core conservatory subject: identifying pitches, intervals, chord quality and rhythm by ear; connects directly to playing by ear and sight-singing.",
  },
  "sdt-wiki": {
    title: "Self-Determination Theory — autonomy, competence, relatedness",
    url: "https://en.wikipedia.org/wiki/Self-Determination_Theory",
    site: "en.wikipedia.org",
    institution: "Self-Determination Theory (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Motivation science: intrinsic motivation thrives when three needs are met — autonomy (choice), competence (progress you can feel), relatedness (connection); extrinsic rewards can undermine intrinsic drive if mishandled.",
  },
  "stage-fright-wiki": {
    title: "Stage fright — performance anxiety is a normal body response",
    url: "https://en.wikipedia.org/wiki/Performance_anxiety",
    site: "en.wikipedia.org",
    institution: "Stage fright (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Adrenaline/sympathetic activation causes racing heart, shaky hands, dry mouth — in beginners and veterans alike; preparation and repeated exposure are the standard countermeasures.",
  },
  "music-lesson-wiki": {
    title: "Music lesson — posture and setup come first in formal instruction",
    url: "https://en.wikipedia.org/wiki/Music_lesson",
    site: "en.wikipedia.org",
    institution: "Music lesson (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "medium",
    notes: "Teachers begin by showing how to sit/hold the instrument; correct posture and position are treated as the foundation technique is built on (section has limited sourcing — reflected in entry confidence).",
  },
  "thai-music-wiki": {
    title: "Music of Thailand — traditional ensembles and modern genres",
    url: "https://en.wikipedia.org/wiki/Music_of_Thailand",
    site: "en.wikipedia.org",
    institution: "Music of Thailand (standard reference)",
    country: "TH",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Traditional instruments reflect far-flung origins (khim — Persian; chakhe — Indian; klong chin — Chinese); luk thung and mor lam are the most popular traditional styles; never-colonized history kept the line unbroken.",
  },
  "gamification-wiki": {
    title: "Gamification — points as feedback, badges as achievements",
    url: "https://en.wikipedia.org/wiki/Gamification",
    site: "en.wikipedia.org",
    institution: "Gamification (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "medium",
    notes: "Points give continuous, immediate feedback and reward; badges visually represent achievements; engagement leverages mastery/achievement/status drives — design must serve feedback, not replace it.",
  },
  "rote-learning-wiki": {
    title: "Rote learning — repetition builds foundations, meaning builds mastery",
    url: "https://en.wikipedia.org/wiki/Rote_learning",
    site: "en.wikipedia.org",
    institution: "Rote learning (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Repetition-based memorization is widely used for foundational knowledge; by itself it does not produce deep understanding — alternatives include meaningful, spaced and active learning.",
  },
  "musical-note-wiki": {
    title: "Musical note — duration values halve, two naming systems",
    url: "https://en.wikipedia.org/wiki/Musical_note",
    site: "en.wikipedia.org",
    institution: "Musical note (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Note values halve down the list (whole→half→quarter→eighth…); American and British names differ (semibreve/minim/crotchet/quaver); notes also carry dynamics and articulation.",
  },
  /* ── Repertoire/forms/patterns + improv/transposition/special-populations
     (gap report 2026-09-17 round 2: eras, forms, left-hand patterns, how to
     teach improvisation, transposition, ADHD/small-hand learners). All read
     2026-09-17, same provenance rules. ── */
  "baroque-music-wiki": {
    title: "Baroque music — 1600-1750, polyphony and the birth of common-practice tonality",
    url: "https://en.wikipedia.org/wiki/Baroque_music",
    site: "en.wikipedia.org",
    institution: "Baroque music (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "1600-1750 era (Bach/Handel/Corelli); dense polyphony — multiple independent melodic lines; formalized common-practice tonality; opera/concerto/sonata genres born.",
  },
  "classical-period-wiki": {
    title: "Classical period — 1750-1820, melody over accompaniment; the fortepiano",
    url: "https://en.wikipedia.org/wiki/Classical_period_(music)",
    site: "en.wikipedia.org",
    institution: "Classical period (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Homophonic texture (clear melody over subordinate chords); variety and contrast prized; the piano (forte-piano, loud-soft) replaced the harpsichord — dynamics became playable.",
  },
  "romantic-music-wiki": {
    title: "Romantic music — 19th century, individualistic/emotional/programmatic",
    url: "https://en.wikipedia.org/wiki/Romantic_music",
    site: "en.wikipedia.org",
    institution: "Romantic music (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "19th-century movement (Chopin/Liszt/Schumann); individualistic, emotional, often inspired by nature/poetry; increased chromaticism; traditional forms loosened.",
  },
  "musical-form-wiki": {
    title: "Musical form — the structure of a piece",
    url: "https://en.wikipedia.org/wiki/Musical_form",
    site: "en.wikipedia.org",
    institution: "Musical form (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Form = the plan of a whole piece; binary/ternary (ABA) structures are among the most common organizational schemes learners meet first.",
  },
  "theme-variations-wiki": {
    title: "Variation (music) — theme restated in altered form",
    url: "https://en.wikipedia.org/wiki/Variation_(music)",
    site: "en.wikipedia.org",
    institution: "Variation form (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Material repeated in altered form — melodic decoration, rhythmic change (syncopation), harmonic substitution, mode shift (major→minor); Mozart K.265 'Twinkle' variations the canonical student example.",
  },
  "sonatina-wiki": {
    title: "Sonatina — a small sonata, the classic student form",
    url: "https://en.wikipedia.org/wiki/Sonatina",
    site: "en.wikipedia.org",
    institution: "Sonatina (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Short, lighter, technically more elementary sonata; Clementi Op.36 No.1 in C is the worldwide first sonatina students meet.",
  },
  "rondo-wiki": {
    title: "Rondo — the refrain form (ABACA)",
    url: "https://en.wikipedia.org/wiki/Rondo",
    site: "en.wikipedia.org",
    institution: "Rondo (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Principal theme returns between contrasting episodes (ABACA, ABACABA); common as a sonatina/sonata finale because the refrain keeps the listener oriented.",
  },
  "alberti-bass-wiki": {
    title: "Alberti bass — low-high-middle-high broken-chord accompaniment",
    url: "https://en.wikipedia.org/wiki/Alberti_bass",
    site: "en.wikipedia.org",
    institution: "Alberti bass (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Broken-chord accompaniment in the order lowest-highest-middle-highest; classical-era signature (Mozart K.545 opens with it); gives smooth sustained flow and rhythmic drive.",
  },
  "ostinato-wiki": {
    title: "Ostinato — persistently repeated motif (riff/vamp in pop and jazz)",
    url: "https://en.wikipedia.org/wiki/Ostinato",
    site: "en.wikipedia.org",
    institution: "Ostinato (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Repeated rhythmic/melodic figure (Boléro, Carol of the Bells, countless pop songs); called riff/vamp in rock and jazz — the engine under melody.",
  },
  "transposition-wiki": {
    title: "Transposition — moving notes up/down by a constant interval",
    url: "https://en.wikipedia.org/wiki/Transposition_(music)",
    site: "en.wikipedia.org",
    institution: "Transposition (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Shifting melody/progression/piece to another key keeping the same interval structure; chromatic (by semitones) vs diatonic (by scale steps) — the app's transpose feature does chromatic.",
  },
  "adhd-simple-wiki": {
    title: "ADHD — attention regulation; hyperfocus on interesting tasks",
    url: "https://simple.wikipedia.org/wiki/Attention_deficit_hyperactivity_disorder",
    site: "simple.wikipedia.org",
    institution: "ADHD (plain-language reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "medium",
    notes: "~1 in 20 children; attention regulation differences — trouble on routine tasks but often hyperfocus on genuinely interesting/urgent ones; implications for short, varied, game-like practice blocks.",
  },
  "young-children-music-wiki": {
    title: "Music education for young children — playful, multi-mode learning",
    url: "https://en.wikipedia.org/wiki/Music_education_for_young_children",
    site: "en.wikipedia.org",
    institution: "Music education for young children (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "medium",
    notes: "Playful introduction (singing/speech/motion); action songs combine musical/vocal/visual/physical modes improving memorization, recall and motor skills; social turn-taking benefits.",
  },
};

/* Countries already covered by a real, read source. Used by the KB seeder to
   label provenance and to make gaps explicit rather than guessed. */
export const COVERAGE = [
  { country: "TH", label: "ไทย", source: "mahidol-music-wiki" },
  { country: "US", label: "สหรัฐอเมริกา", source: "berklee-wiki" },
  { country: "US-2", label: "สหรัฐอเมริกา (conservatory)", source: "juilliard-wiki" },
  { country: "RU", label: "รัสเซีย", source: "moscow-conservatory-wiki" },
  { country: "FR", label: "ฝรั่งเศส", source: "paris-conservatory-wiki" },
  { country: "CN", label: "จีน", source: "ccom-wiki" },
  { country: "JP", label: "ญี่ปุ่น", source: "tokyo-geidai-wiki" },
  { country: "KR", label: "เกาหลีใต้", source: "karts-wiki" },
  { country: "UK", label: "สหราชอาณาจักร", source: "rcm-home" },
];

/* Global topical coverage (theory / pedagogy / practice science) — same idea
   as COVERAGE but for subjects rather than countries, so gaps stay explicit. */
export const GLOBAL_COVERAGE = [
  { area: "theory", label: "ทฤษฎีดนตรีสากล", sources: ["theory-overview-wiki", "harmony-wiki", "chord-wiki", "cadence-wiki", "harmonic-function-wiki", "circle-of-fifths-wiki", "metre-wiki", "rhythm-wiki", "solfege-wiki", "sight-reading-wiki", "improvisation-wiki"] },
  { area: "pedagogy", label: "ระบบการสอนดนตรี", sources: ["suzuki-wiki", "koday-wiki", "orff-wiki", "dalcroze-wiki", "gordon-wiki", "piano-pedagogy-wiki", "taubman-wiki", "music-education-wiki"] },
  { area: "assessment", label: "ระบบตัวชี้วัดระดับ", sources: ["abrsm-wiki", "trinity-wiki", "rcm-toronto-wiki"] },
  { area: "practice-science", label: "วิทยาการการซ้อม", sources: ["practice-wiki", "spaced-repetition-wiki", "testing-effect-wiki", "chunking-wiki"] },
  { area: "piano-craft", label: "วิชาช่างเปียโน (pedal/dynamics/jazz)", sources: ["piano-pedals-wiki", "sustain-pedal-wiki", "dynamics-wiki", "jazz-piano-wiki", "twelve-bar-blues-wiki", "extended-chord-wiki", "slash-chord-wiki", "interval-wiki"] },
  { area: "teacher-craft", label: "วิชาครู (จำ/ฝึกหู/เวที/แรงจูงใจ)", sources: ["music-memory-wiki", "ear-training-wiki", "sdt-wiki", "stage-fright-wiki", "music-lesson-wiki", "thai-music-wiki", "gamification-wiki", "rote-learning-wiki", "musical-note-wiki"] },
  { area: "deep-theory", label: "ทฤษฎีขั้นสูง (modes/inversions/voice-leading/modulation)", sources: ["mode-wiki", "inversion-wiki", "voice-leading-wiki", "modulation-wiki"] },
  { area: "repertoire", label: "ความรู้เพลง (ยุค/ฟอร์ม/แบบแผนมือซ้าย)", sources: ["baroque-music-wiki", "classical-period-wiki", "romantic-music-wiki", "musical-form-wiki", "theme-variations-wiki", "sonatina-wiki", "rondo-wiki", "alberti-bass-wiki", "ostinato-wiki"] },
  { area: "learner-differences", label: "ผู้เรียนเฉพาะกลุ่ม + การย้ายคีย์", sources: ["transposition-wiki", "adhd-simple-wiki", "young-children-music-wiki"] },
];

export function getSource(id) { return SOURCES[id] || null; }

export function listSourceIds() { return Object.keys(SOURCES); }
