/* ── tigamodel/knowledge/university-sources.js ──
   Source registry for university-sourced music knowledge (spec §10-§12).

   Collection method (owner directive 2026-09-17): gather music knowledge
   attributed to leading music universities/conservatories of each country,
   from public internet pages. Every source below was ACTUALLY READ on
   2026-09-17 via its URL (institution site or its Wikipedia article).
   Nothing is invented; if a fact is not backed by a page we could open,
   it is NOT in this file. Content written from these sources is
   PARAPHRASED pedagogical facts (not copied text), each carrying its
   source_id so every KB entry stays traceable (no fake citations — §12).

   License stance: facts about curricula/traditions are ideas/facts (not
   copyrightable expression); paraphrased in our own words; source metadata
   recorded for provenance. No proprietary course materials are reproduced. ── */

export const SOURCES = {
  "mahidol-music-wiki": {
    title: "College of Music, Mahidol University — overview and history",
    url: "https://en.wikipedia.org/wiki/College_of_Music,_Mahidol_University",
    site: "en.wikipedia.org",
    institution: "College of Music, Mahidol University (Thailand)",
    country: "TH",
    institution_url: "http://www.music.mahidol.ac.th",
    read_at: "2026-09-17",
    reliability: "high", // tertiary source with cited facts about the institution
    notes: "First comprehensive music school in Thailand (est. 1994); teaching continuum from age 3 through Ph.D.; large general-public music campus.",
  },
  "berklee-wiki": {
    title: "Berklee College of Music — history and contemporary-music focus",
    url: "https://en.wikipedia.org/wiki/Berklee_College_of_Music",
    site: "en.wikipedia.org",
    institution: "Berklee College of Music (USA)",
    country: "US",
    institution_url: "https://berklee.edu",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Largest independent contemporary-music college; founded around the Schillinger System of harmony and composition; practitioner-taught model; jazz/contemporary emphasis.",
  },
  "berklee-home": {
    title: "Berklee College of Music — official site (areas of study)",
    url: "https://www.berklee.edu/",
    site: "berklee.edu",
    institution: "Berklee College of Music (USA)",
    country: "US",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Official study areas include Music Theory, Ear Training, Harmony as a distinct discipline cluster; Piano as a dedicated performance area.",
  },
  "juilliard-wiki": {
    title: "The Juilliard School — history and structure",
    url: "https://en.wikipedia.org/wiki/Juilliard_School",
    site: "en.wikipedia.org",
    institution: "The Juilliard School (USA)",
    country: "US",
    institution_url: "https://www.juilliard.edu",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Founded 1905 as Institute of Musical Art; music division largest/oldest; pre-college through doctorate training continuum.",
  },
  "moscow-conservatory-wiki": {
    title: "Moscow State Tchaikovsky Conservatory — history",
    url: "https://en.wikipedia.org/wiki/Moscow_Conservatory",
    site: "en.wikipedia.org",
    institution: "Moscow State Tchaikovsky Conservatory (Russia)",
    country: "RU",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Founded 1866 by Nikolai Rubinstein; Tchaikovsky appointed professor of theory and harmony at opening; piano class taught from the earliest years.",
  },
  "paris-conservatory-wiki": {
    title: "Conservatoire de Paris — history and 'French School' tradition",
    url: "https://en.wikipedia.org/wiki/Conservatoire_de_Paris",
    site: "en.wikipedia.org",
    institution: "Conservatoire de Paris / CNSMDP (France)",
    country: "FR",
    institution_url: "https://www.conservatoiredeparis.fr",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Founded 1795; draws on the 'French School' tradition; historic piano faculty include Louise Farrenc, Henri Herz, Antoine François Marmontel.",
  },
  "ccom-wiki": {
    title: "Central Conservatory of Music — programs and scale",
    url: "https://en.wikipedia.org/wiki/Central_Conservatory_of_Music",
    site: "en.wikipedia.org",
    institution: "Central Conservatory of Music (China)",
    country: "CN",
    institution_url: "http://www.ccom.edu.cn",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "National music academy of China (est. 1950); piano among core undergraduate programs; complete ladder from primary schools through doctorate; owns 500+ pianos.",
  },
  "tokyo-geidai-wiki": {
    title: "Tokyo University of the Arts — music faculty history",
    url: "https://en.wikipedia.org/wiki/Tokyo_University_of_the_Arts",
    site: "en.wikipedia.org",
    institution: "Tokyo University of the Arts / Geidai (Japan)",
    country: "JP",
    institution_url: "https://www.geidai.ac.jp/english/",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Music education lineage from Tokyo Music School (1887); national arts university integrating fine arts and music; exchanges with European conservatories.",
  },
  "karts-wiki": {
    title: "Korea National University of Arts (K-Arts) — School of Music",
    url: "https://en.wikipedia.org/wiki/Korea_National_University_of_Arts",
    site: "en.wikipedia.org",
    institution: "Korea National University of Arts (South Korea)",
    country: "KR",
    institution_url: "http://www.karts.ac.kr/",
    read_at: "2026-09-17",
    reliability: "medium-high",
    notes: "National arts university (est. 1993) with a dedicated School of Music among its six schools; conservatory-style training model.",
  },
  "rcm-home": {
    title: "Royal College of Music — official site (programmes, Centre for Performance Science)",
    url: "https://www.rcm.ac.uk/",
    site: "rcm.ac.uk",
    institution: "Royal College of Music (UK)",
    country: "UK",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "London conservatoire (est. 1882); intensive public-performance programme ethos; Centre for Performance Science research (performance psychology/science).",
  },
  /* ── Global music-THEORY references (owner directive 2026-09-17: gather
     theory knowledge from around the world so the model teaches theory and
     practice both well). These are the standard reference articles on the
     specific theory topics, all read 2026-09-17. ── */
  "theory-overview-wiki": {
    title: "Music theory — definition, scope, and the world's theoretical traditions",
    url: "https://en.wikipedia.org/wiki/Music_theory",
    site: "en.wikipedia.org",
    institution: "Music theory (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Three uses of the term (rudiments / scholarly study / general principles); Mesopotamian interval tablets pre-1500 BCE; Chinese theory from numbers 12-5-8; theory exists in all musical cultures.",
  },
  "harmony-wiki": {
    title: "Harmony — vertical and horizontal dimensions, consonance/dissonance, resolution",
    url: "https://en.wikipedia.org/wiki/Harmony",
    site: "en.wikipedia.org",
    institution: "Harmony (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Harmony = combining pitches into chords and chords into progressions; vertical (frequency-space) + horizontal (time-space); consonance/dissonance balance; tensions; Aristoxenus: the listener's ear decides.",
  },
  "chord-wiki": {
    title: "Chord — triads, sevenths, arpeggios, progressions, figured bass",
    url: "https://en.wikipedia.org/wiki/Chord_(music)",
    site: "en.wikipedia.org",
    institution: "Chord (music) (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Triad = most common chord; arpeggio = notes sounded separately; dominant seventh became the fixture of the common practice period; chord notation systems (figured bass, Roman numerals, Nashville numbers).",
  },
  "cadence-wiki": {
    title: "Cadence — the four main types and their chord progressions",
    url: "https://en.wikipedia.org/wiki/Cadence",
    site: "en.wikipedia.org",
    institution: "Cadence (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Authentic V-I, half x-V, plagal IV-I, deceptive V-vi; US vs British naming (authentic/perfect, deceptive/interrupted); cadences are strong tonic indicators — Lowinsky: 'the cradle of tonality'.",
  },
  "harmonic-function-wiki": {
    title: "Harmonic function — Tonic/Subdominant/Dominant and the two theories",
    url: "https://en.wikipedia.org/wiki/Function_(music)",
    site: "en.wikipedia.org",
    institution: "Function (music) (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Riemann's German function theory (T/S/D letters) vs the Viennese Roman-numeral theory (Sechter, Schoenberg, Schenker); both descend from Rameau 1722; the three primary triads F-C-G produce the major scale.",
  },
  "circle-of-fifths-wiki": {
    title: "Circle of fifths — key layout, closely related keys, modulation",
    url: "https://en.wikipedia.org/wiki/Circle_of_fifths",
    site: "en.wikipedia.org",
    institution: "Circle of fifths (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Twelve pitch classes in ascending perfect fifths; adjacent keys = closely related signatures; harmonic progressions commonly move between adjacent keys; Pythagorean comma → equal temperament.",
  },
  "metre-wiki": {
    title: "Metre (music) — pulse hierarchy, accent patterns, time signatures",
    url: "https://en.wikipedia.org/wiki/Meter_(music)",
    site: "en.wikipedia.org",
    institution: "Metre (music) (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Metre = recurring accent pattern over the pulse; beats exist only once some pulses are accented; listeners hold a metric hierarchy on minimal evidence; duple/triple subdivision; world systems (tala etc.).",
  },
  "rhythm-wiki": {
    title: "Rhythm — strong/weak element grouping, distinguished from pulse and metre",
    url: "https://en.wikipedia.org/wiki/Rhythm",
    site: "en.wikipedia.org",
    institution: "Rhythm (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Rhythm = grouping of unaccented beats around an accented one; distinct from pulse (the steady stream) and metre (the accent framework); timing of sounds and silences on a human scale.",
  },
  "solfege-wiki": {
    title: "Solfège — Guido of Arezzo, fixed vs movable do, solmization worldwide",
    url: "https://en.wikipedia.org/wiki/Solf%C3%A8ge",
    site: "en.wikipedia.org",
    institution: "Solfège (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "From Guido of Arezzo's 11th-c. hymn syllables ut-re-mi-fa-sol-la; fixed do (syllable = pitch) vs movable do (syllable = degree); a mnemonic for audiating pitch — the international ear-training tool.",
  },
  "sight-reading-wiki": {
    title: "Sight-reading — eye-hand span, working memory, audiation link",
    url: "https://en.wikipedia.org/wiki/Sight-reading",
    site: "en.wikipedia.org",
    institution: "Sight-reading (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Reading + performing unseen notation; skilled readers look further ahead (eye-hand span) storing notes in working memory; depends on short-term musical memory; silent sight-reading = audiation.",
  },
  "improvisation-wiki": {
    title: "Musical improvisation — history and harmonic frameworks",
    url: "https://en.wikipedia.org/wiki/Musical_improvisation",
    site: "en.wikipedia.org",
    institution: "Musical improvisation (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Improvisation over a chord framework was central from Bach to Chopin (cadenza, prelude, figured-bass realisation, ornamentation); raga = the improvisational framework in Indian classical music.",
  },

  /* ── Global teaching methods + practice science (owner directive: the model
     must teach well, not just know theory). All read 2026-09-17. ── */
  "suzuki-wiki": {
    title: "Suzuki method — mother-tongue approach, environment, review",
    url: "https://en.wikipedia.org/wiki/Suzuki_method",
    site: "en.wikipedia.org",
    institution: "Suzuki method (Shinichi Suzuki, Japan)",
    country: "JP",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Talent Education: ability is made by environment, not inborn; learn by ear before reading (children speak before they read); daily listening; memorisation; constant review of every piece; small steps, scaled to the child; no aptitude gate.",
  },
  "koday-wiki": {
    title: "Kodály method — sing first, child-developmental sequencing, solfège",
    url: "https://en.wikipedia.org/wiki/Kod%C3%A1ly_method",
    site: "en.wikipedia.org",
    institution: "Kodály method (Zoltán Kodály, Hungary)",
    country: "HU",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Voice is the first instrument — sing before play; experience (listen/sing/move) before notation; rhythm syllables (ta, ti-ti); easiest-concept-first sequencing; constant review through games; UNESCO intangible heritage 2016.",
  },
  "orff-wiki": {
    title: "Orff Schulwerk — elemental music, learning by doing, play-based",
    url: "https://en.wikipedia.org/wiki/Orff_Schulwerk",
    site: "en.wikipedia.org",
    institution: "Orff Schulwerk (Carl Orff & Gunild Keetman, Germany)",
    country: "DE",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Elemental music close to a child's world of play; every concept learned by DOING; break each activity into its simplest form and present one step at a time; improvisation and ostinato as core materials; no pressure of being judged.",
  },
  "dalcroze-wiki": {
    title: "Dalcroze eurhythmics — rhythm through the body, movement before notation",
    url: "https://en.wikipedia.org/wiki/Dalcroze_eurhythmics",
    site: "en.wikipedia.org",
    institution: "Dalcroze eurhythmics (Émile Jaques-Dalcroze, Switzerland)",
    country: "CH",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Rhythm lives in the body: experience a concept through movement before its visual symbol; kinesthetic foundation for steady beat; influenced Kodály/Orff/Suzuki; improvisation as one of the three lesson pillars.",
  },
  "gordon-wiki": {
    title: "Gordon Music Learning Theory — audiation and learning sequences",
    url: "https://en.wikipedia.org/wiki/Gordon_Music_Learning_Theory",
    site: "en.wikipedia.org",
    institution: "Gordon music learning theory (Edwin Gordon, US)",
    country: "US",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Audiation = hearing and comprehending music that is not physically present ('audiation is to music what thought is to language'); discrimination → inference learning ladder: aural/oral → verbal association → symbolic; pattern vocabulary over isolated notes.",
  },
  "piano-pedagogy-wiki": {
    title: "Piano pedagogy — the field, teacher factors, lineage (Taubman, Neuhaus …)",
    url: "https://en.wikipedia.org/wiki/Piano_pedagogy",
    site: "en.wikipedia.org",
    institution: "Piano pedagogy (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Teaching quality factors: performance competence, repertoire knowledge, adapting to personality/learning style; lineage Czerny → Leschetizky → Neuhaus; Taubman and Whiteside re-imagined technique as coordinated motion, not finger strength.",
  },
  "taubman-wiki": {
    title: "Dorothy Taubman — the Taubman Approach (coordinated motion, injury-free playing)",
    url: "https://en.wikipedia.org/wiki/Dorothy_Taubman",
    site: "en.wikipedia.org",
    institution: "Dorothy Taubman (US)",
    country: "US",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Technique from coordinated motions of the whole arm — forearm rotation, shaping, grouping, in-and-out — not finger force; famous for rehabilitating injured pianists (incl. Leon Fleisher); thumb-under rethought as passing under with rotation.",
  },
  "abrsm-wiki": {
    title: "ABRSM — the world's graded music exam ladder (est. 1889)",
    url: "https://en.wikipedia.org/wiki/ABRSM",
    site: "en.wikipedia.org",
    institution: "ABRSM (UK)",
    country: "UK",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Grades 1-8 + diplomas across 90+ countries, 600k+ candidates a year; graded ladder = the de-facto global scaffold: pieces + technique (scales) + supporting tests (sight-reading, aural) per grade.",
  },
  "trinity-wiki": {
    title: "Trinity College London — graded exams with flexible repertoire choice",
    url: "https://en.wikipedia.org/wiki/Trinity_College_London",
    site: "en.wikipedia.org",
    institution: "Trinity College London (UK)",
    country: "UK",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Grades Initial-8 since 1877; three assessment categories (pieces / technical work / supporting tests incl. improvisation); candidates choose among pieces — flexibility within a scaffold.",
  },
  "rcm-toronto-wiki": {
    title: "The Royal Conservatory of Music — the North American graded system",
    url: "https://en.wikipedia.org/wiki/Royal_Conservatory_of_Music",
    site: "en.wikipedia.org",
    institution: "The Royal Conservatory of Music (Canada)",
    country: "CA",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Est. 1886 Toronto; RCM certificate program grades 1-10 + ARCT used across Canada/US; elementary/intermediate/advanced teacher certification tied to the same ladder.",
  },
  "practice-wiki": {
    title: "Deliberate practice (K. Anders Ericsson) — how one practises beats how long",
    url: "https://en.wikipedia.org/wiki/Practice_(learning_method)",
    site: "en.wikipedia.org",
    institution: "Practice (learning method) — deliberate practice",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Expertise reflects HOW one practises, not repetition count: break the skill into chunks, work on weaknesses at the edge of ability, with immediate feedback; without feedback practice can be ineffective or even detrimental.",
  },
  "spaced-repetition-wiki": {
    title: "Spaced repetition — Ebbinghaus's forgetting curve, expanding intervals",
    url: "https://en.wikipedia.org/wiki/Spaced_repetition",
    site: "en.wikipedia.org",
    institution: "Spaced repetition (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Review at expanding intervals defeats the forgetting curve (Ebbinghaus 1880s); recall success doubles the next interval, failure resets it — the schedule mechanic behind keeping reviewed repertoire alive.",
  },
  "testing-effect-wiki": {
    title: "Testing effect / retrieval practice — recalling beats re-reading",
    url: "https://en.wikipedia.org/wiki/Testing_effect",
    site: "en.wikipedia.org",
    institution: "Testing effect (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Actively retrieving from memory (playing from memory, naming the key, quizzing) produces more durable learning than passive re-exposure; active vs passive repetition distinguished since Bacon 1620, James 1890.",
  },
  "chunking-wiki": {
    title: "Chunking — working-memory limits and meaningful groups",
    url: "https://en.wikipedia.org/wiki/Chunking_(psychology)",
    site: "en.wikipedia.org",
    institution: "Chunking (psychology) (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "Working memory holds a handful of items — but a chunk of 2-6 associated items counts as ONE; grouping notes into hands/figures/phrases is what makes long passages learnable at all.",
  },
  "music-education-wiki": {
    title: "Music education — the 20th-century method families, one map",
    url: "https://en.wikipedia.org/wiki/Music_education",
    site: "en.wikipedia.org",
    institution: "Music education (standard reference)",
    country: "GLOBAL",
    read_at: "2026-09-17",
    reliability: "high",
    notes: "The method map in one place: Dalcroze (movement), Kodály (voice), Orff (elemental doing), Suzuki (mother tongue), Gordon (audiation), Carabo-Cone (concrete environment), MMCP (creation), WMP (culture).",
  },
};

/* Countries already covered by a real, read source. Used by the KB seeder to
   label provenance and to make gaps explicit rather than guessed. */
export const COVERAGE = [
  { country: "TH", label: "ไทย", source: "mahidol-music-wiki" },
  { country: "US", label: "สหรัฐอเมริกา", source: "berklee-wiki" },
  { country: "US-2", label: "สหรัฐอเมริกา (conservatory)", source: "juilliard-wiki" },
  { country: "RU", label: "รัสเซีย", source: "moscow-conservatory-wiki" },
  { country: "FR", label: "ฝรั่งเศส", source: "paris-conservatory-wiki" },
  { country: "CN", label: "จีน", source: "ccom-wiki" },
  { country: "JP", label: "ญี่ปุ่น", source: "tokyo-geidai-wiki" },
  { country: "KR", label: "เกาหลีใต้", source: "karts-wiki" },
  { country: "UK", label: "สหราชอาณาจักร", source: "rcm-home" },
];

/* Global topical coverage (theory / pedagogy / practice science) — same idea
   as COVERAGE but for subjects rather than countries, so gaps stay explicit. */
export const GLOBAL_COVERAGE = [
  { area: "theory", label: "ทฤษฎีดนตรีสากล", sources: ["theory-overview-wiki", "harmony-wiki", "chord-wiki", "cadence-wiki", "harmonic-function-wiki", "circle-of-fifths-wiki", "metre-wiki", "rhythm-wiki", "solfege-wiki", "sight-reading-wiki", "improvisation-wiki"] },
  { area: "pedagogy", label: "ระบบการสอนดนตรี", sources: ["suzuki-wiki", "koday-wiki", "orff-wiki", "dalcroze-wiki", "gordon-wiki", "piano-pedagogy-wiki", "taubman-wiki", "music-education-wiki"] },
  { area: "assessment", label: "ระบบตัวชี้วัดระดับ", sources: ["abrsm-wiki", "trinity-wiki", "rcm-toronto-wiki"] },
  { area: "practice-science", label: "วิทยาการการซ้อม", sources: ["practice-wiki", "spaced-repetition-wiki", "testing-effect-wiki", "chunking-wiki"] },
];

export function getSource(id) { return SOURCES[id] || null; }

export function listSourceIds() { return Object.keys(SOURCES); }
