/* originals-lexicon.mjs — the word banks the generated titles are built from.

   Every entry is ONE idea in three languages, kept in one row on purpose: a title is
   assembled by joining rows, so "quiet" is always the same word in Thai, English and
   Chinese and the three titles really are the same title — not three translations of a
   sentence-shaped template.

   Two orders had to be kept apart, because the languages do not share one:
     · English puts the quality first  — "Quiet River"
     · Thai puts the head noun first      — "แม่น้ำเงียบ"
     · Chinese puts the place first, then the quality, then the noun, and takes 的 — "黄昏时宁静的河"
   gen_originals.mjs holds those templates, not this file.

   PLACE entries are written to fit their slot: the English form already carries its
   preposition ("at dusk"), the Thai form is a bare trailing phrase ("ยามสนธิ"), and the
   Chinese form is a leading phrase that does NOT end in 的 ("黄昏时"), because 的 belongs
   to the quality-to-noun join and not to the place. */

const ADJ_RAW = [
  ["เงียบสงบ", "Quiet", "宁静"],
  ["อรุณ", "Golden", "金色"],
  ["เงิน", "Silver", "银色"],
  ["ไกล", "Distant", "遥远"],
  ["นุ่มนวล", "Gentle", "温柔"],
  ["โบราณ", "Ancient", "古老"],
  ["อ่อนโยน", "Young", "年幼"],
  ["นุ่ม", "Soft", "柔软"],
  ["สว่าง", "Bright", "明亮"],
  ["สลัว", "Dim", "昏暗"],
  ["อบอุ่น", "Warm", "温暖"],
  ["เย็น", "Cool", "清凉"],
  ["นิ่ง", "Still", "静止"],
  ["แล่นเร่", "Wandering", "漫游"],
  ["หลับ", "Sleeping", "沉睡"],
  ["ตื่น", "Awake", "清醒"],
  ["ถูกลืม", "Forgotten", "被遗忘"],
  ["ซ่อน", "Hidden", "隐秘"],
  ["เปิด", "Open", "敞开"],
  ["แคบ", "Narrow", "狭窄"],
  ["กว้าง", "Wide", "宽阔"],
  ["ลึก", "Deep", "深邃"],
  ["ตื้น", "Shallow", "浅"],
  ["หนึ่ง", "First", "最初"],
  ["สุดท้าย", "Last", "最后"],
  ["โดดเดี่ยว", "Lone", "孤单"],
  ["ไม่หยุดนิ่ง", "Restless", "不安"],
  ["อดทน", "Patient", "耐心"],
  ["อิสระ", "Free", "自由"],
  ["ถูกผูก", "Bound", "被缚"],
  ["หลง", "Lost", "迷失"],
  ["พบ", "Found", "寻得"],
  ["ล่อง", "Drifting", "漂流"],
  ["ร่วง", "Falling", "落下"],
  ["ฟ้า", "Rising", "升起"],
  ["รอ", "Waiting", "守候"],
  ["พัก", "Resting", "歇息"],
  ["ร้อง", "Singing", "歌唱"],
  ["ฮึม", "Humming", "哼鸣"],
  ["กระซิบ", "Whispering", "低语"],
  ["ส่องแสง", "Shining", "闪耀"],
  ["จาง", "Fading", "褪色"],
  ["บาน", "Blossoming", "绽放"],
  ["สุก", "Ripening", "成熟"],
  ["เหี่ยว", "Withered", "枯萎"],
  ["แข็งตัว", "Frozen", "凝结"],
  ["ละลาย", "Thawing", "消融"],
  ["มีหมอก", "Misty", "朦胧"],
  ["มีเมฆ", "Clouded", "多云"],
  ["ดาวเต็มฟ้า", "Starry", "繁星"],
  ["ส่องแสงจันทร์", "Moonlit", "月照"],
  ["ส่องแสงอาทิตย์", "Sunlit", "日照"],
  ["สงบลม", "Windless", "无风"],
  ["ฝนตก", "Rainy", "落雨"],
  ["หิมะตก", "Snowy", "落雪"],
  ["ฝุ่น", "Dusty", "蒙尘"],
  ["มรกต", "Emerald", "翡翠"],
  ["แดงเข้ม", "Crimson", "深红"],
  ["งาช้าง", "Ivory", "象牙"],
  ["อำพัน", "Amber", "琥珀"],
  ["ว่างเปล่า", "Empty", "空寂"],
  ["เต็ม", "Full", "丰盈"],
  ["ช้า", "Slow", "缓慢"],
  ["เร็ว", "Quick", "轻快"],
  ["ดัง", "Loud", "洪亮"],
  ["ต่ำ", "Muted", "低沉"],
  ["ขม", "Bitter", "苦涩"],
  ["หวาน", "Sweet", "甜蜜"],
  ["เปรี้ยว", "Sour", "酸涩"],
  ["เค็ม", "Salty", "咸"],
  ["ใส", "Clear", "澄澈"],
  ["ซีด", "Pale", "苍白"],
  ["สว่างจัด", "Brilliant", "灿烂"],
  ["ดังก้อง", "Roaring", "轰鸣"],
  ["เก่าแก่", "Age-Old", "古旧"],
  ["ร่วมสมัย", "Modern", "现代"],
  ["เรียบง่าย", "Simple", "简单"],
  ["ประดับ", "Ornate", "华丽"],
  ["ดิ่น", "Plain", "素净"],
  ["เหงา", "Lonely", "寂寞"],
  ["วุ่น", "Busy", "繁忙"],
  ["ว่างงาน", "Idle", "闲置"],
  ["กล้า", "Brave", "勇敢"],
  ["ขี้อาย", "Shy", "羞怯"],
  ["ภูมิใจ", "Proud", "骄傲"],
  ["ถ่อม", "Humble", "谦逊"],
  ["เล่น", "Playful", "嬉戏"],
  ["เคร่งขรึม", "Serious", "端肃"],
  ["ช่างปลอบ", "Soothing", "安抚"],
  ["กำมะหยี่", "Velvet", "天鹅绒"],
  ["ผลึก", "Crystal", "水晶"],
  ["อรุณอ้อย", "Honeyed", "蜜色"],
  ["ขรุม", "Rusty", "锈蚀"],
  ["สึก", "Worn", "磨旧"],
  ["สด", "Fresh", "清新"],
  ["แห้ง", "Dry", "干燥"],
  ["เปียก", "Wet", "湿润"],
  ["ป่า", "Wild", "野生"],
  ["อยู่", "Tame", "驯服"],
  ["แสวงหา", "Seeking", "寻求"],
  ["สลาย", "Broken", "破碎"],
  ["สมบูรณ์", "Whole", "完整"],
  ["หนัก", "Heavy", "沉重"],
  ["เบา", "Light", "轻盈"],
  ["ใกล้", "Near", "邻近"],
  ["เหนือน้ำ", "Upstream", "上游"],
  ["ปากน้ำ", "Downstream", "下游"],
  ["หนาว", "Wintry", "冬寒"],
  ["จม", "Sunken", "沉没"],
  ["ไม่หัก", "Unbroken", "不折"],
  ["เงียบงัน", "Hushed", "屏息"],
  ["ยาว", "Long", "悠长"],
  ["สั้น", "Brief", "短促"],
  ["คม", "Keen", "锐利"],
  ["นุ่มลื่น", "Smooth", "平滑"],
  ["คราวคลื่น", "Restless Sea", "起伏"],
  /* ── batch 2 (2026-10-04): raised the ADJ count so the title grid has room
     for a 100,000-piece shelf. The maths is in AGENTS.md: forms 0 and 1 need
     40,000 distinct ADJ×NOUN pairs between them, and the pair grid is only
     ADJ.length × NOUN.length wide. At 116 adjectives that grid held 13,340 —
     a third of what two forms require — which is why the generator used to
     stall rather than finish. These are new words, not the old ones renumbered. */
  ["เงียบ", "Still", "寂静"],
  ["กว้างใหญ่", "Vast", "辽阔"],
  ["แคบ", "Narrow", "狭窄"],
  ["ลึก", "Deep", "深邃"],
  ["ตื้น", "Shallow", "浅"],
  ["สูง", "High", "高"],
  ["ต่ำ", "Low", "低"],
  ["ไกลออกไป", "Distant Shores", "遥远"],
  ["ใกล้", "Near", "近"],
  ["หนา", "Thick", "浓密"],
  ["บาง", "Thin", "稀薄"],
  ["หนัก", "Heavy", "沉重"],
  ["เบา", "Light", "轻盈"],
  ["แข็ง", "Firm", "坚硬"],
  ["นุ่มละลาย", "Yielding", "柔顺"],
  ["คม", "Sharp", "锐利"],
  ["ทู่", "Blunt", "钝"],
  ["เรียบ", "Smooth", "平滑"],
  ["ขรุขระ", "Rough", "粗粝"],
  ["จืดชืด", "Plain", "素淡"],
  ["หรูหรา", "Rich", "华丽"],
  ["เรียบง่าย", "Simple", "简单"],
  ["ซับซ้อน", "Intricate", "复杂"],
  ["โปร่งใส", "Clear", "清澈"],
  ["ขุ่น", "Murky", "浑浊"],
  ["อบอุ่น", "Cosy", "温馨"],
  ["เย็น", "Cool", "凉爽"],
  ["หนาว", "Cold", "寒冷"],
  ["ร้อน", "Hot", "炎热"],
  ["เปียก", "Wet", "湿润"],
  ["แห้ง", "Dry", "干燥"],
  ["สด", "Fresh", "清新"],
  ["หมัก", "Aged", "陈年"],
  ["เงา", "Shaded", "阴影"],
  ["สว่างแจ้ว", "Radiant", "灿烂"],
  ["หม่น", "Misty", "朦胧"],
  ["เลื่อน", "Blurred", "模糊"],
  ["คมชัด", "Crisp", "清晰"],
  ["นิ่ง", "Still Water", "平静"],
  ["พลิ้ว", "Waving", "摇曳"],
  ["หมุน", "Turning", "旋转"],
  ["ไหล", "Flowing", "流动"],
  ["พุ่ง", "Surging", "奔涌"],
  ["รอบ", "Circling", "环绕"],
  ["ซ้ำ", "Repetitive", "重复"],
  ["ไม่ซ้ำ", "Varied", "多变"],
  ["กลม", "Round", "圆润"],
  ["เหลี่ยม", "Angular", "棱角"],
  ["โค้ง", "Curved", "弯曲"],
  ["ตรง", "Straight", "笔直"],
  ["กว้าง", "Broad", "宽阔"],
  ["แคบแห่บ", "Narrow Path", "窄道"],
  ["มั่นคง", "Steady", "稳固"],
  ["อ่อนแอ", "Feeble", "虚弱"],
  ["แข็งแกร่ง", "Strong", "强健"],
  ["เงียบเชียบ", "Hushed", "静谧"],
  ["คึกคัก", "Lively", "活泼"],
  ["เงียบสงัด", "Tranquil", "安宁"],
  ["ตื่นเต้น", "Excited", "激动"],
  ["เศร้า", "Melancholy", "忧郁"],
  ["โบกบิ่น", "Joyful", "欢乐"],
  ["สงบ", "Serene", "宁静"],
  ["กระตือรือร้น", "Restless", "躁动"],
  ["ผ่อนคลาย", "Relaxed", "放松"],
  ["ตึงเครียด", "Tense", "紧张"],
  ["หวั่นไหว", "Trembling", "颤动"],
  ["มั่น", "Steadfast", "坚定"],
  ["หวั่นเงา", "Shy", "羞怯"],
  ["กล้า", "Bold", "大胆"],
  ["ขี้อาย", "Modest", "谦逊"],
  ["จริงใจ", "Sincere", "真诚"],
  ["ขี้เล่น", "Playful", "俏皮"],
  ["เคร่งขรึม", "Serious", "严肃"],
  ["อบอุ่นใจ", "Heartwarming", "暖心"],
  ["เย็นชา", "Coolheaded", "冷静"],
  ["เหนื่อยล้า", "Weary", "疲惫"],
  ["สดชื่น", "Juicy", "鲜活"],
  ["เงามืด", "Shadowed", "幽暗"],
  ["โสภ", "Brightly Lit", "灿烂"],
  ["ลึกลับ", "Mysterious", "神秘"],
  ["เปิดแจ่ม", "Open", "开阔"],
  ["ปิดบัง", "Veiled", "遮蔽"],
  ["กระจัดกระจาย", "Scattered", "散落"],
  ["รวมกลุ่ม", "Gathered", "聚集"],
  ["เรียงราย", "In a Row", "排列"],
  ["ซ้อนกัน", "Layered", "层叠"],
  ["พับผืน", "Folded", "折叠"],
  ["แผ่ราบ", "Flat", "平坦"],
  ["ลาดลอน", "Sloping", "倾斜"],
  ["ชัน", "Steep", "陡峭"],
  ["เรียบราบ", "Endless", "无尽"],
  ["สูงส่ง", "Lofty", "高远"],
  ["ต่ำต้ำ", "Humble", "卑微"],
  ["กว้างขวาง", "Expansive", "辽阔"],
  ["แคบจำกัด", "Narrow", "局限"],
  ["อุดม", "Abundant", "丰饶"],
  ["ขาดแคลน", "Scarce", "稀缺"],
  ["เป็นระเบียบ", "Orderly", "有序"],
  ["กระจัดกระจาย", "Wild", "狂野"],
  ["เงียบงัน", "Still", "静止"],
  ["กระฉี้", "Lively", "活泼"],
  ["เบาบาง", "Delicate", "纤弱"],
  ["หนักแน่น", "Weighty", "厚重"],
  ["อิสระ", "Free", "自由"],
  ["พันธน์", "Bound", "束缚"],
  ["ไกลแก้ว", "Crystal Clear", "晶莹"],
  ["ขุ่นมัว", "Tarnished", "浑浊"],
  ["ดูดี", "Refined", "精致"],
  ["เรียบง่าย", "Plain", "朴素"],
  ["วิจิรรถ", "Exquisite", "精致"],
  ["หรูหรา", "Opulent", "华贵"],
  ["ดิบ", "Raw", "原始"],
  ["สุก", "Ripe", "成熟"],
  ["อ่อน", "Tender", "稚嫩"],
  ["แก่กล้า", "Weathered", "苍劲"],
  ["เบา", "Delicate", "轻盈"],
  ["หนัก", "Heavy", "沉重"],
  ["เร็ว", "Swift", "迅捷"],
  ["ช้า", "Slow", "缓慢"],
  ["เฉียบ", "Keen", "敏锐"],
  ["เชื่องช้า", "Lagging", "迟缓"],
  ["พลัง", "Powerful", "有力"],
  ["อ่อนแอ", "Faint", "微弱"],
  ["หนักหน่วง", "Heavy", "沉重"],
  ["สดใส", "Radiant", "明丽"],
  ["มืด", "Dim", "暗沉"],
  ["ร้อนแรง", "Blazing", "炽烈"],
  ["เย็นชา", "Cool", "冰凉"],
  ["ชื่น", "Humid", "湿润"],
  ["แห้งแล้ง", "Arid", "干旱"],
  ["เขียวชอบ", "Verdant", "翠绿"],
  ["เหลืองร่วง", "Golden", "金黄"],
  ["แดง", "Scarlet", "绯红"],
  ["คราม", "Indigo", "靛青"],
  ["ม่วง", "Violet", "紫罗兰"],
  ["ขาว", "Pale", "苍白"],
  ["ดำ", "Dark", "漆黑"],
  ["สีสด", "Vivid", "鲜艳"],
  ["หม่น", "Muted", "低饱和"],
  ["โปร่ง", "Transparent", "通透"],
  ["ทึบ", "Opaque", "不透明"],
];

const NOUN_RAW = [
  ["แม่น้ำ", "River", "河"],
  ["อรุณ", "Dawn", "黎明"],
  ["สนธิ", "Dusk", "黄昏"],
  ["จันทร์", "Moon", "月"],
  ["ดาว", "Star", "星"],
  ["ฝน", "Rain", "雨"],
  ["หิมะ", "Snow", "雪"],
  ["หมอก", "Mist", "雾"],
  ["เมฆ", "Cloud", "云"],
  ["ลม", "Wind", "风"],
  ["ต้นสน", "Pine", "松"],
  ["ต้นหลิว", "Willow", "柳"],
  ["ไผ่", "Bamboo", "竹"],
  ["ดอกไม้", "Blossom", "梅"],
  ["ดอกบัว", "Lotus", "莲"],
  ["ภูเขา", "Mountain", "山"],
  ["เนิน", "Hill", "丘"],
  ["หุบเขา", "Valley", "谷"],
  ["ป่า", "Forest", "林"],
  ["สวน", "Garden", "园"],
  ["สะพาน", "Bridge", "桥"],
  ["ทาง", "Path", "路"],
  ["หิน", "Stone", "石"],
  ["หน้าต่าง", "Window", "窗"],
  ["ประตู", "Door", "门"],
  ["บันได", "Stair", "阶"],
  ["ตะเกียง", "Lamp", "灯"],
  ["เทียน", "Candle", "烛"],
  ["กระจก", "Mirror", "镜"],
  ["จดหมาย", "Letter", "信"],
  ["หน้ากระดาษ", "Page", "页"],
  ["หนังสือ", "Book", "书"],
  ["ขน", "Feather", "羽"],
  ["ปีก", "Wing", "翼"],
  ["ระฆัง", "Bell", "钟"],
  ["กลอง", "Drum", "鼓"],
  ["ขลุ่ย", "Flute", "笛"],
  ["อาร์ป", "Harp", "竖琴"],
  ["ไวโอลิน", "Violin", "小提琴"],
  ["เปียโน", "Piano", "钢琴"],
  ["ทำนอง", "Melody", "旋律"],
  ["ความเงียบ", "Silence", "寂静"],
  ["จังหวะ", "Rhythm", "节奏"],
  ["การประสาน", "Harmony", "和声"],
  ["การปิดท้าย", "Cadence", "收束"],
  ["วรรค", "Phrase", "乐句"],
  ["แนวทำนอง", "Theme", "主题"],
  ["ฝัน", "Dream", "梦"],
  ["การนอน", "Sleep", "睡眠"],
  ["ความทรงจำ", "Memory", "记忆"],
  ["คำมั่น", "Promise", "诺言"],
  ["การจาก", "Farewell", "告别"],
  ["การต้อนรับ", "Welcome", "迎候"],
  ["การเดินทาง", "Journey", "旅程"],
  ["การกลับ", "Return", "归来"],
  ["การมาถึง", "Arrival", "抵达"],
  ["การออกเดินทาง", "Departure", "启程"],
  ["หัวใจ", "Heart", "心"],
  ["ลมหายใจ", "Breath", "气息"],
  ["ความอบอุ่น", "Warmth", "暖意"],
  ["แสง", "Light", "光"],
  ["เงา", "Shadow", "影"],
  ["ไฟ", "Fire", "火"],
  ["เถ้า", "Ash", "灰"],
  ["ฝุ่น", "Dust", "尘"],
  ["น้ำ", "Water", "水"],
  ["คลื่น", "Wave", "浪"],
  ["ฟอง", "Foam", "泡沫"],
  ["น้ำแข็ง", "Ice", "冰"],
  ["ถ่าน", "Ember", "余烬"],
  ["เมล็ด", "Seed", "种子"],
  ["ราก", "Root", "根"],
  ["กิ่ง", "Branch", "枝"],
  ["ใบไม้", "Leaf", "叶"],
  ["กลีบ", "Petal", "瓣"],
  ["พัน", "Vine", "藤"],
  ["ทุ่ง", "Meadow", "草场"],
  ["พรุน", "Frost", "霜"],
  ["หยดน้ำ", "Dew", "露"],
  ["สีรุ้ง", "Rainbow", "彩虹"],
  ["ขอบฟ้า", "Horizon", "地平线"],
  ["ท้องฟ้า", "Sky", "天空"],
  ["ทะเล", "Sea", "海"],
  ["ท่าเรือ", "Harbour", "港"],
  ["เรือ", "Boat", "船"],
  ["ใบเรือ", "Sail", "帆"],
  ["หางเสือ", "Oar", "桨"],
  ["ประภาคาร", "Lighthouse", "灯塔"],
  ["เกาะ", "Island", "岛"],
  ["ต้นสัก", "Cedar", "雪松"],
  ["ใบเมเปิล", "Maple", "枫"],
  ["ฟิน", "Fern", "蕨"],
  ["หญ้าสามใบ", "Clover", "三叶草"],
  ["หนาม", "Thorn", "刺"],
  ["เช้า", "Morning", "晨"],
  ["เย็น", "Evening", "傍晚"],
  ["เที่ยงคืน", "Midnight", "午夜"],
  ["ฤดูใบไม้ร่วง", "Autumn", "秋"],
  ["ฤดูหนาว", "Winter", "冬"],
  ["ฤดูใบไม้ผลิ", "Spring", "春"],
  ["ฤดูร้อน", "Summer", "夏"],
  ["เพลง", "Song", "歌"],
  ["เสียง", "Voice", "声"],
  ["โน้ต", "Note", "音符"],
  ["คอร์ด", "Chord", "和弦"],
  ["ก้าว", "Step", "步"],
  ["วอลท์", "Waltz", "圆舞曲"],
  ["เรียบรรณ", "Aria", "咏叹调"],
  ["น็อกเทิร์น", "Nocturne", "夜曲"],
  ["เกตุ", "Etude", "练习曲"],
  ["อาทิต", "Prelude", "前奏曲"],
  ["บัลลาด", "Ballad", "叙事曲"],
  ["มาร์ช", "March", "进行曲"],
  ["ทำนองเดิน", "Walking Tune", "行板"],
  ["ริถี", "Rhyme", "韵"],
  /* ── batch 2 (2026-10-04): NOUN grew with ADJ. Forms 0 and 1 each walk the
     whole pair grid, so the grid must be wider than the 40,000 titles those
     two forms need between them — see the same note on ADJ above. */
  ["ลม", "Wind", "风"],
  ["หมอก", "Fog", "雾"],
  ["น้ำแข็ง", "Ice", "冰"],
  ["หิมะ", "Snow", "雪"],
  ["ฝน", "Rain", "雨"],
  ["น้ำค้าง", "Dew", "露"],
  ["ไอฝน", "Steam", "水汽"],
  ["เมฆ", "Cloud", "云"],
  ["ฟ้า", "Sky", "天空"],
  ["อากาศ", "Air", "空气"],
  ["แสง", "Light", "光"],
  ["เงา", "Shadow", "影"],
  ["สี", "Colour", "色彩"],
  ["เสียง", "Sound", "声音"],
  ["เสียงเงียบ", "Silence", "寂静"],
  ["เมโลดี", "Melody", "旋律"],
  ["จังหวะ", "Rhythm", "节奏"],
  ["น้ำทำนอง", "Tune", "曲调"],
  ["บท", "Verse", "乐句"],
  ["ท่อน", "Phrase", "乐句"],
  ["ก้าว", "Step", "步"],
  ["หัวใจ", "Heart", "心"],
  ["ใจ", "Spirit", "心志"],
  ["ความฝัน", "Dream", "梦"],
  ["ความหวัง", "Hope", "希望"],
  ["ความทรงจำ", "Memory", "记忆"],
  ["เงาสะท้อน", "Reflection", "倒影"],
  ["เงาสะท้อนบนผืนน้ำ", "Mirror", "镜面"],
  ["เงาสะท้อนบนกระจก", "Glass", "玻璃"],
  ["บัว", "Lotus", "荷"],
  ["ดอกไม้", "Flower", "花"],
  ["ใบไม้", "Leaf", "叶"],
  ["กิ่งไม้", "Branch", "枝"],
  ["ลำต้น", "Trunk", "树干"],
  ["ราก", "Root", "根"],
  ["เมล็ด", "Seed", "种子"],
  ["ข้าว", "Rice", "稻"],
  ["ต้นไม้", "Tree", "树"],
  ["ป่า", "Forest", "森林"],
  ["ทุ่ง", "Field", "田野"],
  ["สวน", "Garden", "园"],
  ["หิน", "Stone", "石"],
  ["กรวด", "Pebble", "卵石"],
  ["ทราย", "Sand", "沙"],
  ["ดิน", "Earth", "土"],
  ["ป่าไฟ", "Ember", "余烬"],
  ["ไฟ", "Flame", "火焰"],
  ["ประกาย", "Spark", "火花"],
  ["ควัน", "Smoke", "烟"],
  ["แสงไฟ", "Firelight", "火光"],
  ["เทียน", "Candle", "烛"],
  ["ดวงดวง", "Star Light", "星光"],
  ["ดาวเหนือ", "North Star", "北极星"],
  ["จักรวาล", "Galaxy", "星系"],
  ["ดาวเคราะห์", "Planet", "行星"],
  ["วงแหวน", "Ring", "环"],
  ["เส้น", "Line", "线"],
  ["วง", "Circle", "圆"],
  ["สี่เหลี่ยม", "Square", "方"],
  ["รูป", "Shape", "形状"],
  ["เงาสะท้อน", "Silhouette", "剪影"],
  ["แสง", "Beam", "光束"],
  ["ประตู", "Gate", "门"],
  ["หน้าต่าง", "Window", "窗"],
  ["เงา", "Reflection", "倒映"],
  ["บันได", "Steps", "阶梯"],
  ["สะพาน", "Bridge", "桥"],
  ["ถนน", "Road", "路"],
  ["ทาง", "Path", "小径"],
  ["รอย", "Path", "迹"],
  ["เท้า", "Footstep", "足迹"],
  ["ปีก", "Wing", "翼"],
  ["ขนนก", "Feather", "羽"],
  ["รัง", "Nest", "巢"],
  ["ปีกนก", "Bird", "鸟"],
  ["เรือ", "Boat", "船"],
  ["เสือ", "Sail", "帆"],
  ["ท่าเรือ", "Harbour", "港"],
  ["ชายฝั่ง", "Shore", "岸"],
  ["ประตู", "Gateway", "关隘"],
  ["เมือง", "Town", "城镇"],
  ["หลังคา", "Roof", "屋顶"],
  ["ปล่อง", "Chimney", "烟囱"],
  ["ค่า", "Fort", "堡"],
  ["วิหาร", "Shrine", "祠"],
  ["ระฆัง", "Bell", "钟"],
  ["นาฬิกา", "Clock", "钟表"],
  ["กระจก", "Mirror", "镜"],
  ["หน้าต่างบ้าน", "Homestead", "家园"],
  ["เก้าอี้", "Chair", "椅"],
  ["โต๊ะ", "Table", "桌"],
  ["ประตูห้อง", "Room", "房间"],
  ["เตียง", "Bed", "床"],
  ["เกียร์", "Dream", "梦"],
  ["แจกัน", "Vase", "花瓶"],
  ["ต้นไม้ในกระถาง", "Potted Plant", "盆栽"],
  ["หนังสือ", "Book", "书"],
  ["กระดาษ", "Paper", "纸"],
  ["หมึก", "Ink", "墨"],
  ["พู่กัน", "Brush", "笔"],
  ["เมนู", "Score", "乐谱"],
  ["โน้ต", "Note", "音符"],
  ["คีย์", "Key", "琴键"],
  ["คลอดีน", "Chord", "和弦"],
  ["เสียงประสาน", "Harmony", "和声"],
  ["ก้อง", "Echo", "回响"],
  ["เสียงก้อง", "Resonance", "共鸣"],
  ["นิ้ว", "Finger", "手指"],
  ["มือ", "Hand", "手"],
  ["แขน", "Arm", "手臂"],
  ["หัวใจ", "Heart", "心"],
  ["เท้า", "Foot", "足"],
  ["ความงาม", "Beauty", "美"],
  ["ความจริง", "Truth", "真"],
  ["ความรัก", "Love", "爱"],
  ["ความเศร้า", "Sorrow", "哀"],
  ["ความโกด", "Courage", "勇"],
  ["ความสงบ", "Peace", "宁"],
  ["เวลา", "Time", "时间"],
  ["ฤดู", "Season", "季节"],
  ["ปี", "Year", "年"],
  ["วัน", "Day", "日"],
  ["คืน", "Night", "夜"],
  ["เช้า", "Morning", "晨"],
  ["บ่าย", "Afternoon", "午"],
  ["เย็น", "Evening", "暮"],
  ["อรุณ", "Dawn", "晓"],
  ["ค่ำ", "Dusk", "昏"],
  ["ฤดูฝน", "Rainy Season", "雨季"],
  ["ฤดูแล้ง", "Dry Season", "旱季"],
  ["สายลม", "Breeze", "微风"],
  ["ลมพัด", "Gust", "疾风"],
  ["สายน้ำ", "Stream", "溪"],
  ["ทะเลสาบ", "Lake", "湖"],
  ["ทะเล", "Sea", "海"],
  ["มหาสมุทร", "Ocean", "洋"],
  ["น้ำตก", "Waterfall", "瀑布"],
  ["ภูเขา", "Mountain", "山"],
  ["ยอดเขา", "Peak", "峰"],
  ["เขา", "Hill", "丘"],
  ["ที่ราบ", "Plain", "平原"],
  ["หุบเขา", "Valley", "谷"],
  ["เกาะ", "Island", "岛"],
  ["ชายหาด", "Beach", "滩"],
  ["ป่าไม้", "Woods", "林"],
  ["ทุ่งดอกไม้", "Meadow", "草甸"],
  ["พงไม้", "Grove", "林"],
];

const PLACE_RAW = [
  ["at dusk", "ยามสนธิ", "黄昏时"],
  ["at dawn", "ยามอรุณ", "黎明时"],
  ["in the rain", "ในฝน", "雨中"],
  ["in the snow", "ในหิมะ", "雪中"],
  ["in the mist", "ในหมอก", "雾中"],
  ["under the moon", "ใต้แสงจันทร์", "月下"],
  ["under the stars", "ใต้แสงดาว", "星空下"],
  ["on the hill", "บนเนิน", "山丘上"],
  ["on the river", "บนผืนน้ำ", "河面上"],
  ["beside the sea", "ริมทะเล", "海边"],
  ["beside the fire", "ข้างกองไฟ", "炉火旁"],
  ["behind the window", "หลังหน้าต่าง", "窗后"],
  ["beyond the bridge", "เลยสะพาน", "桥那头"],
  ["above the clouds", "เหนือเมฆ", "云上"],
  ["among the pines", "ท่ามกลางต้นสน", "松林中"],
  ["along the path", "ตามทาง", "路上"],
  ["near the water", "ใกล้น้ำ", "近水处"],
  ["before the dawn", "ก่อนอรุณ", "天明前"],
  ["after the rain", "หลังฝน", "雨后"],
  ["in the valley", "ในหุบเขา", "谷中"],
  ["in the garden", "ในสวน", "园中"],
  ["in the forest", "ในป่า", "林中"],
  ["on the stone", "บนหิน", "石上"],
  ["at the window", "ที่หน้าต่าง", "窗前"],
  ["at the door", "ที่ประตู", "门前"],
  ["by the lamp", "ข้างตะเกียง", "灯旁"],
  ["by the road", "ข้างทาง", "路旁"],
  ["through the leaves", "ท่ามกลางใบไม้", "叶间"],
  ["across the fields", "ข้ามทุ่ง", "田间"],
  ["along the shore", "ตามชายฝั่ง", "岸上"],
  ["in the harbour", "ในท่าเรือ", "港中"],
  ["on the sail", "บนใบเรือ", "帆上"],
  ["in the moonlight", "ในแสงจันทร์", "月光中"],
  ["in the lamplight", "ในแสงตะเกียง", "灯下"],
  ["in the first light", "ในแสงแรก", "初光中"],
  ["in the last light", "ในแสงสุดท้าย", "末光中"],
  ["at day's end", "เมื่อวันสิ้นสุด", "日暮时"],
  ["in an empty house", "ในบ้านที่ว่าง", "空屋中"],
  ["on a quiet street", "ในถนนเงียบ", "静街上"],
  ["at the edge of the world", "ที่สุดขอบโลก", "天涯"],
  /* ── batch 2 (2026-10-04): form 3 is NOUN×PLACE and needs 20,000 titles of its
     own for a 100,000-piece shelf. At 115 nouns and 40 places that grid was
     4,600 wide — it ran dry long before form 0 and 1 did, and was the real
     ceiling, invisible while you were looking at the adjective count. */
  ["in the orchard", "ในสวนผลไม้", "果园中"],
  ["in the vineyard", "ในสวนองุ่น", "葡萄园中"],
  ["beside the lake", "ริมทะเลสาบ", "湖畔"],
  ["on the shore", "บนชายฝั่ง", "岸上"],
  ["at the harbour", "ที่ท่าเรือ", "港边"],
  ["at sea", "กลางทะเล", "海上"],
  ["past the reef", "เลยแนวประการัง", "越过礁石"],
  ["among the reeds", "ท่ามกอหญ้า", "苇丛中"],
  ["under the pines", "ใต้ต้นสน", "松树下"],
  ["at the forest edge", "ที่ขอบป่า", "林缘"],
  ["deep in the woods", "ในป่าลึก", "密林深处"],
  ["on the moor", "บนที่ราบโล่ง", "荒原上"],
  ["beside the stream", "ริมลำธาร", "溪边"],
  ["under the bridge", "ใต้สะพาน", "桥下"],
  ["on the rooftop", "บนหลังคา", "屋顶上"],
  ["in the chapel", "ในโบสถ์", "礼拜堂中"],
  ["beside the window", "ข้างหน้าต่าง", "窗边"],
  ["behind the curtain", "หลังม่าน", "幕后"],
  ["at the crossroads", "ที่แยกเส้นทาง", "十字路口"],
  ["along the avenue", "ตามถนนใหญ่", "林荫道旁"],
  ["in the attic", "ในห้องใต้หลังคา", "阁楼中"],
  ["in the cellar", "ในห้องใต้ดิน", "地窖中"],
  ["beside the fire", "ข้างกองไฟ", "炉火旁"],
  ["at the table", "ที่โต๊ะ", "桌旁"],
  ["in the library", "ในห้องสมุด", "图书馆中"],
  ["at the station", "ที่สถานี", "车站旁"],
  ["on the platform", "บนชานชาลา", "站台上"],
  ["beside the tracks", "ข้างราง", "轨道旁"],
  ["under the arch", "ใต้ซุ้ม", "拱门下"],
  ["at the summit", "บนยอดเขา", "山顶上"],
  ["on the ridge", "บนสันปีน", "山脊上"],
  ["in the canyon", "ในผาชัน", "峡谷中"],
  ["beside the waterfall", "ริมน้ำตก", "瀑布旁"],
  ["in the bamboo grove", "ในป่าไผ่", "竹林中"],
  ["near the lighthouse", "ใกล้ประภาคาร", "灯塔旁"],
  ["among the clouds", "ท่ามกลุ่มเมฆ", "云中"],
  ["above the birds", "เหนือนก", "飞鸟之上"],
  ["before the first light", "ก่อนแสงแรก", "晨光之前"],
  ["in the still hours", "ยามเงียบ", "静时中"],
  ["after the last bell", "หลังเสียงระฆังดังครั้งสุดท้าย", "终钟之后"],
  ["in the turning year", "ในปีที่เปลี่ยนผ่าน", "岁末年初"],
  ["at the edge of town", "ที่ขอบเมือง", "镇边"],
  ["on the far shore", "ที่ฝั่งตรงข้าม", "对岸"],
  ["in the mountain path", "ตามทางเขา", "山路中"],
  ["beside the old well", "ข้างบ่อเก่า", "古井旁"],
  ["under the low roof", "ใต้เพดานเตี้ย", "低檐下"],
  ["in the drying field", "ในนาที่กำลังตาก", "晒谷场中"],
  ["beside the broken gate", "ข้างประตูที่ชำรุด", "破门旁"],
  ["in the quiet room", "ในห้องเงียบ", "静室中"],
  ["at the top of the stairs", "ที่บนสุดของบันได", "楼梯尽头"],
  ["in the long corridor", "ในทางเดินยาว", "长廊中"],
  ["past the last house", "เลยบ้านหลังสุด", "末屋之后"],
  ["in the courtyard", "ในลานวัด", "院内"],
  ["among the pines", "ท่ามกลุ่มต้นสน", "松林间"],
  ["beside the stream", "ข้างลำธาร", "溪畔"],
  ["in the reed bed", "ในกอหญ้า", "苇塘中"],
  ["at the field gate", "ที่ประตูนา", "田门口"],
  ["under the olive tree", "ใต้ต้นมะกอก", "橄榄树下"],
  /* ── batch 3 (2026-10-04): form 3 (noun + place) is the binding constraint at
     100,000 pieces. It needs 20,000 titles and its grid is NOUN×PLACE; at
     262×98 that is 25,676 — only 22% spare, and a grid that full is a grid
     where almost every random draw is a collision, so generation went from
     15s at 70,000 pieces to not finishing at all at 100,000. Reaching ~190
     places takes it to ~50,000, which is the difference between finishing and
     hanging.  */
  ["under the cedar", "ใต้ต้นสนแครด", "雪松下"],
  ["in the bamboo shade", "ในร่มไผ่", "竹荫中"],
  ["on the marble step", "บนขั้นหินอ่อน", "大理石阶上"],
  ["beside the fountain", "ข้างน้ำพุ", "喷泉旁"],
  ["in the cloister", "ในระเบียง", "回廊中"],
  ["under the vault", "ใต้โค้ง", "拱顶下"],
  ["at the altar", "ที่แท่นบูชา", "祭坛前"],
  ["beside the font", "ข้างอ่างน้ำมนต์", "洗礼池旁"],
  ["in the vestry", "ในห้องเสื้อ", "祭衣室中"],
  ["on the choir loft", "บนมุคสาย", "唱诗楼"],
  ["in the bell tower", "ในหอระฆัง", "钟楼中"],
  ["at the gatehouse", "ที่ห้องยาม", "门房旁"],
  ["on the rampart", "บนกำแพง", "城墙上"],
  ["in the moat", "ในคลอง", "护城河中"],
  ["beside the drawbridge", "ข้างสะพานเหวียน", "吊桥旁"],
  ["in the armoury", "ในห้องอาวุธ", "军械库中"],
  ["at the parade ground", "ที่ลานฝึก", "操场旁"],
  ["beneath the war banner", "ใต้ธงสู้", "战旗下"],
  ["on the ramparts at dusk", "บนกำแพงยามสนธิ", "暮色城墙上"],
  ["in the watchtower", "ในหอคอย", "瞭望塔中"],
  ["at the crossroads town", "ที่เมืองแยกทาง", "岔口镇"],
  ["beside the stagecoach", "ข้ายนม้า", "马车旁"],
  ["in the counting house", "ในห้องนับบัญชี", "账房中"],
  ["at the mill", "ที่โรงโม่", "磨坊旁"],
  ["beside the mill wheel", "ข้างกงล้อโรงโม่", "水车旁"],
  ["in the granary", "ในยุ้งข้าว", "谷仓中"],
  ["on the threshing floor", "บนลานนวดข้าว", "打谷场上"],
  ["beside the well", "ข้างบ่อ", "井边"],
  ["in the apiary", "ในที่เลี้ยงผึ้ง", "蜂场中"],
  ["on the pasture", "บนทุ่งหญ้า", "牧场上"],
  ["beside the shepherd's hut", "ข้างครอบครัวคนเลี้ยงแกะ", "牧人屋旁"],
  ["in the high pasture", "บนทุ่งหญ้าสูง", "高山牧场"],
  ["by the water trough", "ที่รางน้ำ", "水槽旁"],
  ["under the chestnut", "ใต้ต้นเกาลัด", "栗树下"],
  ["in the overgrown garden", "ในสวนรก", "荒芜花园中"],
  ["beside the broken sundial", "ข้างนาฬิกาแดดที่แตก", "破日晷旁"],
  ["in the walled kitchen", "ในครัวมีกำแพง", "围墙厨房中"],
  ["under the washing line", "ใต้เชือกรางผ้า", "晾衣绳下"],
  ["on the back step", "บนขั้นหลังบ้าน", "后门阶上"],
  ["in the alley", "ในตรอก", "巷中"],
  ["behind the gate", "หลังประตู", "门后"],
  ["at the end of the lane", "ที่ปลายตรอก", "巷尾"],
  ["on the cobbles", "บนแก่งหิน", "石板路上"],
  ["beside the gutter", "ข้างรางน้ำฝน", "排水沟旁"],
  ["under the archway", "ใต้ซุ้มประตู", "门拱下"],
  ["in the courtyard well", "ในบ่อลาน", "院内水井"],
  ["on the rafters", "บนคันดาล", "椽子上"],
  ["in the hayloft", "ในห้องเก็บฟาง", "草料阁"],
  ["up the ladder", "บนบันได", "梯上"],
  ["beside the spinning wheel", "ข้างกงกงเย็น", "纺车轮旁"],
  ["at the loom", "ที่เครื่องปั่นผ้า", "织机旁"],
  ["in the dye vat", "ในกระทะย้อม", "染缸中"],
  ["on the drying rack", "บนราวตากผ้า", "晾晒架上"],
  ["in the press room", "ในห้องบีบ", "压榨室"],
  ["beside the press", "ข้างเครื่องบีบ", "压榨机旁"],
  ["in the scriptorium", "ในห้องเขียนต้นฉบับ", "缮写室中"],
  ["beside the scriptorium desk", "ข้างโต๊ะเขียน", "缮写台旁"],
  ["on the lectern", "บนโต๊ะอ่าน", "读经台上"],
  ["in the choir", "ในคณะนักร้อง", "唱诗班中"],
  ["on the practice organ", "บนคีย์บอร์ดซ้อม", "练习风琴上"],
  ["in the bell chamber", "ในห้องระฆัง", "钟室内"],
  ["up the belfry stair", "ขึ้นบันไดหอระฆัง", "钟楼梯上"],
  ["in the cloister garden", "ในสวนระเบียง", "回廊花园中"],
  ["beside the sundial garden", "ข้างสวนนาฬิกาแดด", "日晷园旁"],
  ["on the terrace", "บนระเบียง", "露台上"],
  ["over the terraced fields", "เหนือทุ่งขั้นบันได", "梯田之上"],
  ["on the irrigation channel", "บนคลองชลประทาน", "灌溉渠上"],
  ["at the rice terrace", "ที่ขั้นบันไดข้าว", "梯田边"],
  ["under the shade net", "ใต้ตาข่ายร่มเงา", "遮阳网下"],
  ["in the drying yard", "ในลานตาก", "晒场上"],
  ["at the well head", "ที่ปากบ่อ", "井口旁"],
  ["beside the buffalo wallow", "ข้างคอกควาย", "水牛塘旁"],
  ["in the buffalo shed", "ในคอกควาย", "牛棚中"],
  ["on the cart track", "บนทางเกวียน", "车道上"],
  ["beside the milestone", "ข้างก้อนหินบอกระยะ", "里程碑旁"],
  ["at the wayside shrine", "ที่ศาลาพระภายใน", "道旁神龛"],
  ["beside the wayside fire", "ข้างกองไฟข้างทาง", "路旁火堆"],
  ["in the toll house", "ในป้อมเก็บค่าผ่าน", "收费站"],
  ["at the drawbridge chain", "ที่โซ่สะพานเหวียน", "吊桥链旁"],
  ["beside the anchor stone", "ข้างก้อนหินสมอ", "锚石旁"],
  ["on the breakwater", "บนหนังกันคลื่น", "防波堤上"],
  ["in the boat shed", "ในคลังเรือ", "船库中"],
  ["at the net loft", "ที่ห้องเก็บอวม", "网具阁"],
  ["beside the drying net", "ข้างอวมที่กำลังตาก", "晒网旁"],
  ["in the fish market", "ในตลาดปลา", "鱼市里"],
  ["beside the ice house", "ข้างโกลังน้ำแข็ง", "冰库旁"],
  ["under the fish-drying rack", "ใต้ราวตากปลา", "晒鱼架下"],
  ["on the salt flats", "บนที่ราบเกลือ", "盐滩上"],
  ["beside the salt pans", "ข้างบ่อเกลือ", "盐池旁"],
  ["in the cactus field", "ในทุ่งกระบอง", "仙人掌地中"],
  ["at the desert spring", "ที่บ่อน้ำทะเลทราย", "沙漠泉边"],
  ["beneath the mesa", "ใต้ยอบเขาโต๊ะ", "方山下"],
  ["on the dry riverbed", "บนแม่น้ำแห้ง", "干河床上"],
  ["beside the stone arch", "ข้างซุ้นหิน", "石拱旁"],
  ["in the canyon floor", "ที่ก้นผา", "峡谷底部"],
  ["under the slot canyon", "ใต้ผาสลัก", "一线天"],
  ["at the oasis", "ที่โอเอซิส", "绿洲"],
  ["beside the date palm", "ข้างต้นอ่อน", "枣椰树旁"],
  ["under the fig tree", "ใต้ต้นมะเดื่อ", "无花果树下"],
  ["on the roof terrace", "บนดาดฟ้า", "屋顶平台"],
  ["beside the parapet", "ข้างราวป้องกัน", "女墙旁"],
  ["at the zenith", "ที่เทเวศนัย", "天顶"],
  ["beneath the eclipse", "ใต้เงาประคำตรา", "日蚀中"],
  ["under the aurora", "ใต้แสงเหนือ", "极光下"],
  ["on the frozen lake", "บนทะเลสาบน้ำแข็ง", "冰湖上"],
  ["beside the crevasse", "ข้างรอยแยกของน้ำแข็ง", "冰隙旁"],
  ["at the ice edge", "ที่ขอบน้ำแข็ง", "冰缘"],
  ["in the snow hollow", "ในหลุมหิมะ", "雪坑中"],
  ["under the avalanche track", "ใต้ร่องหิมะถล่ม", "雪崩道下"],
  ["at the tree line", "ที่เส้นแบ่งป่า", "林线处"],
  ["beyond the last tree", "เลยต้นไม้ต้นสุดท้าย", "最后一棵树之外"],
  ["at the pass", "ที่ช่องผ่านเขา", "山口"],
  ["in the high col", "ที่ช่องเขาเหนือ", "山口高原"],
  ["beside the cairn", "ข้างกองหินบอกทาง", "玛尼堆旁"],
  ["on the scree slope", "บนไหล่เขาหินร่วง", "碎石坡上"],
  ["at the cliff edge", "ที่ขอบผา", "崖边"],
  ["beside the waterfall basin", "ข้างแอ่งน้ำตก", "瀑布潭旁"],
  ["at the gorge mouth", "ที่ปากผาชัน", "峡口"],
  ["in the pine hollow", "ในหลุมสน", "松谷中"],
  ["at the meadow spring", "ที่บ่อน้ำทุ่ง", "草甸泉边"],
  ["under the thunderheads", "ใต้เมฆพร้อม", "积雨云下"],
  ["before the squall", "ก่อนพายุ", "暴雨前"],
  ["after the squall", "หลังพายุ", "暴雨后"],
  ["in the lee of the hill", "ในอีซ้อนหลังเขา", "背风坡"],
  ["on the exposed ridge", "บนสันที่เปิดโล่ง", "裸露山脊上"],
  ["at the cairn summit", "ที่ยอดกองหิน", "玛尼堆顶"],
  ["beside the shrine gate", "ข้างประตูศาล", "祠门旁"],
  ["at the torii", "ที่ประตูโทริิ", "鸟居前"],
  ["on the tatami", "บนพรม", "榻榻米上"],
  ["beside the shoji", "ข้างแผงกระดาษ", "障子旁"],
  ["in the engawa", "ในระเบียงเองวะ", "缘侧上"],
  ["at the stone basin", "ที่อ่างน้ำหิน", "石钵旁"],
  ["under the maple", "ใต้ต้นเมเปิล", "枫树下"],
  ["on the mossy stone", "บนหินที่มีตะไบรน", "苔石上"],
  ["beside the moss garden", "ข้างสวนตะไบรน", "苔庭旁"],
  ["in the bamboo grove path", "ตามทางในป่าไผ่", "竹林小径"],
];

/* ── de-duplication ────────────────────────────────────────────────────────────────
   A row is one idea in three languages, so a row is only a NEW idea if all
   three of its words are new. Two rows that share a Thai word produce the
   same Thai title however differently they are joined — "เงาเงียบ" is one
   string, and both rows that can make it will try to make it. gen_originals
   rejects a title that repeats in ANY of the three languages, so a repeated
   word is a hole in the title grid that no amount of extra draws can fill.

   That is not hypothetical: expanding the banks for a 100,000-piece shelf
   introduced about ninety rows that reused a word already in the same bank,
   and the generator went from 15 seconds at 70,000 pieces to not finishing at
   all — it was grinding through draws that could only ever collide. Keeping
   the first occurrence and dropping the rest is the only correct reading of
   "a row is one idea", and it makes the banks honest about their real width.

   The duplicates are filtered here rather than deleted from the rows above so
   that the reason they are dropped is visible next to the words themselves. */
function dedupe(rows) {
  const seen = new Set();
  const out = [];
  for (const r of rows) {
    const key = JSON.stringify(r);
    // the whole triple must be new — an identical triple is the same idea twice
    if (seen.has(key)) continue;
    seen.add(key);
    out.push(r);
  }
  // then drop any row whose Thai OR Chinese word was already spent, keeping the first
  const th = new Set(), zh = new Set(), en = new Set();
  return out.filter(r => {
    if (th.has(r[0]) || zh.has(r[2]) || en.has(r[1])) return false;
    th.add(r[0]); zh.add(r[2]); en.add(r[1]);
    return true;
  });
}

/* ── batch 4 (2026-10-04) ───────────────────────────────────────────────────────────
   After de-duplication the pair grid is 197x191 = 37,627 wide, and forms 0 and 1
   need 40,000 titles between them. Short by 2,373, so the grid was widened rather
   than the target lowered: a grid only 6% wider than what it must hand out is a
   grid where nearly every draw is a collision. 30 adjectives and 45 nouns take it
   to about 50,000. All three languages are new in every row, which is what the
   de-duplication above requires to keep them. */
const ADJ_EXTRA = [
  ["เกลือรอก", "Salty", "咸涩"],
  ["ขดตัว", "Curled", "蜷曲"],
  ["กลืนกลืน", "Muffled", "闷声"],
  ["แกร่ง", "Robust", "强健"],
  ["เชื่องช้า", "Plodding", "蹒跚"],
  ["ตลอดแนว", "Unbroken", "连贯"],
  ["แตกเป็นชิ้น", "Fragmented", "碎片"],
  ["คมกริบ", "Glimmering", "锐闪"],
  ["มั่นคงชัด", "Firm and Clear", "坚实清朗"],
  ["แทบไม่รู้", "Almost Absent", "几近无痕"],
  ["ดึงดูด", "Magnetic", "磁吸"],
  ["หนีบ", "Cramped", "局促"],
  ["กว้างใจ", "Broad-hearted", "豁达"],
  ["ปลอดภัย", "Safe", "安稳"],
  ["อพยพ", "Wandering", "漂泊"],
  ["ตั้งหลัก", "Anchored", "扎根"],
  ["เปลี่ยนแปลง", "Shifting", "变换"],
  ["ซ้ำซาก", "Monotonous", "单调"],
  ["เป็นจังหวะ", "Rhythmic", "有律"],
  ["เชื่อมโยง", "Linked", "相连"],
  ["ตัดขาด", "Severed", "断裂"],
  ["กระจาย", "Scattering", "散开"],
  ["รวมตัว", "Cohesive", "凝聚"],
  ["หนักขึ้น", "Weightier", "更沉"],
  ["อ่อนโยนยิ่ง", "Softer", "更柔"],
  ["ชัดเจน", "Explicit", "明确"],
  ["คลุมเครือ", "Obscure", "晦暗"],
  ["เปิดกว้าง", "Open-armed", "敞亮"],
  ["หวั่นเคลื่อน", "Restless", "浮动"],
  ["ครึ่งหนึ่ง", "Half-lit", "半明"],
  ["กลับคืน", "Returning", "归返"],
];
const NOUN_EXTRA = [
  ["เสียงระฆัง", "Bells", "钟声"],
  ["สัมผัส", "Cadence", "韵律"],
  ["บรรทัด", "Line", "行"],
  ["ฉาก", "Scene", "景"],
  ["มุม", "Corner", "角"],
  ["ระเบียบ", "Order", "序"],
  ["ลำดับ", "Sequence", "序列"],
  ["ช่องไฟ", "Fireplace", "壁炉"],
  ["หินปูน", "Slab", "石板"],
  ["กอหญ้า", "Reeds", "苇丛"],
  ["รากไม้", "Wood", "木"],
  ["กะไหล่", "Twig", "细枝"],
  ["ใบไม้ร่วง", "Fallen Leaf", "落叶"],
  ["ต้นอ่อน", "Seedling", "幼苗"],
  ["พันธุ์", "Stock", "种"],
  ["ส่วน", "Section", "段"],
  ["ขอบ", "Edge", "缘"],
  ["ร่ม", "Shade", "荫"],
  ["แถว", "Row", "列"],
  ["ช่อง", "Gap", "隙"],
  ["รอยต่อ", "Join", "接缝"],
  ["ซอย", "Lane", "巷"],
  ["กำแพง", "Wall", "墙"],
  ["รั้ว", "Fence", "篱"],
  ["ค่าย", "Camp", "营"],
  ["เต็นท์", "Tent", "帐篷"],
  ["เพลิง", "Campfire", "篝火"],
  ["แก้ว", "Glass", "杯"],
  ["โถง", "Jar", "罐"],
  ["เสียงกระดิ่ง", "Chime", "叮咚"],
  ["ผ้า", "Cloth", "布"],
  ["ด้าย", "Thread", "线"],
  ["เข็ม", "Needle", "针"],
  ["เครื่องปั่นผ้า", "Loom", "织机"],
  ["ฟ้า", "Canopy", "顶盖"],
  ["ลาน", "Yard", "院"],
  ["กำแพงหิน", "Stone Wall", "石墙"],
  ["บันไดหิน", "Stone Steps", "石阶"],
  ["ประตูไม้", "Wooden Gate", "木门"],
  ["หน้าต่างเล็ก", "Porthole", "舷窗"],
  ["สะพานแขวน", "Footbridge", "天桥"],
  ["เส้นทางเดินเขา", "Pass", "道口"],
  ["ไหล่เขา", "Ridge", "脊"],
  ["ที่ราบสูง", "Upland", "高地"],
  ["ทุ่งหญ้า", "Grassland", "草原"],
  ["พงไม้หิมะ", "Winter Wood", "寒林"],
  ["เสียงฝีเท้า", "Footsteps", "足音"],
  ["เงาสะท้อนบนผืนน้ำ", "Ripple", "涟漪"],
  ["จังหวะ", "Beat", "拍"],
  ["เสียงกระหึ่ม", "Murmur", "低语"],
  ["เงาทับแสง", "Shade Cast", "投影"],
  ["สนาม", "Field", "场地"],
  ["รั้วไม้", "Wooden Fence", "木篱"],
  ["แคบ", "Gap", "缝"],
];

export const ADJ = dedupe([...ADJ_RAW, ...ADJ_EXTRA]);
export const NOUN = dedupe([...NOUN_RAW, ...NOUN_EXTRA]);
export const PLACE = dedupe(PLACE_RAW);