/* originals-lexicon.mjs — the word banks the generated titles are built from.

   Every entry is ONE idea in three languages, kept in one row on purpose: a title is
   assembled by joining rows, so "quiet" is always the same word in Thai, English and
   Chinese and the three titles really are the same title — not three translations of a
   sentence-shaped template.

   Two orders had to be kept apart, because the languages do not share one:
     · English puts the quality first  — "Quiet River"
     · Thai puts the head noun first      — "แม่น้ำเงียบ"
     · Chinese puts the place first, then the quality, then the noun, and takes 的 — "黄昏时宁静的河"
   gen_originals.mjs holds those templates, not this file.

   PLACE entries are written to fit their slot: the English form already carries its
   preposition ("at dusk"), the Thai form is a bare trailing phrase ("ยามสนธิ"), and the
   Chinese form is a leading phrase that does NOT end in 的 ("黄昏时"), because 的 belongs
   to the quality-to-noun join and not to the place. */

export const ADJ = [
  ["เงียบสงบ", "Quiet", "宁静"],
  ["อรุณ", "Golden", "金色"],
  ["เงิน", "Silver", "银色"],
  ["ไกล", "Distant", "遥远"],
  ["นุ่มนวล", "Gentle", "温柔"],
  ["โบราณ", "Ancient", "古老"],
  ["อ่อนโยน", "Young", "年幼"],
  ["นุ่ม", "Soft", "柔软"],
  ["สว่าง", "Bright", "明亮"],
  ["สลัว", "Dim", "昏暗"],
  ["อบอุ่น", "Warm", "温暖"],
  ["เย็น", "Cool", "清凉"],
  ["นิ่ง", "Still", "静止"],
  ["แล่นเร่", "Wandering", "漫游"],
  ["หลับ", "Sleeping", "沉睡"],
  ["ตื่น", "Awake", "清醒"],
  ["ถูกลืม", "Forgotten", "被遗忘"],
  ["ซ่อน", "Hidden", "隐秘"],
  ["เปิด", "Open", "敞开"],
  ["แคบ", "Narrow", "狭窄"],
  ["กว้าง", "Wide", "宽阔"],
  ["ลึก", "Deep", "深邃"],
  ["ตื้น", "Shallow", "浅"],
  ["หนึ่ง", "First", "最初"],
  ["สุดท้าย", "Last", "最后"],
  ["โดดเดี่ยว", "Lone", "孤单"],
  ["ไม่หยุดนิ่ง", "Restless", "不安"],
  ["อดทน", "Patient", "耐心"],
  ["อิสระ", "Free", "自由"],
  ["ถูกผูก", "Bound", "被缚"],
  ["หลง", "Lost", "迷失"],
  ["พบ", "Found", "寻得"],
  ["ล่อง", "Drifting", "漂流"],
  ["ร่วง", "Falling", "落下"],
  ["ฟ้า", "Rising", "升起"],
  ["รอ", "Waiting", "守候"],
  ["พัก", "Resting", "歇息"],
  ["ร้อง", "Singing", "歌唱"],
  ["ฮึม", "Humming", "哼鸣"],
  ["กระซิบ", "Whispering", "低语"],
  ["ส่องแสง", "Shining", "闪耀"],
  ["จาง", "Fading", "褪色"],
  ["บาน", "Blossoming", "绽放"],
  ["สุก", "Ripening", "成熟"],
  ["เหี่ยว", "Withered", "枯萎"],
  ["แข็งตัว", "Frozen", "凝结"],
  ["ละลาย", "Thawing", "消融"],
  ["มีหมอก", "Misty", "朦胧"],
  ["มีเมฆ", "Clouded", "多云"],
  ["ดาวเต็มฟ้า", "Starry", "繁星"],
  ["ส่องแสงจันทร์", "Moonlit", "月照"],
  ["ส่องแสงอาทิตย์", "Sunlit", "日照"],
  ["สงบลม", "Windless", "无风"],
  ["ฝนตก", "Rainy", "落雨"],
  ["หิมะตก", "Snowy", "落雪"],
  ["ฝุ่น", "Dusty", "蒙尘"],
  ["มรกต", "Emerald", "翡翠"],
  ["แดงเข้ม", "Crimson", "深红"],
  ["งาช้าง", "Ivory", "象牙"],
  ["อำพัน", "Amber", "琥珀"],
  ["ว่างเปล่า", "Empty", "空寂"],
  ["เต็ม", "Full", "丰盈"],
  ["ช้า", "Slow", "缓慢"],
  ["เร็ว", "Quick", "轻快"],
  ["ดัง", "Loud", "洪亮"],
  ["ต่ำ", "Muted", "低沉"],
  ["ขม", "Bitter", "苦涩"],
  ["หวาน", "Sweet", "甜蜜"],
  ["เปรี้ยว", "Sour", "酸涩"],
  ["เค็ม", "Salty", "咸"],
  ["ใส", "Clear", "澄澈"],
  ["ซีด", "Pale", "苍白"],
  ["สว่างจัด", "Brilliant", "灿烂"],
  ["ดังก้อง", "Roaring", "轰鸣"],
  ["เก่าแก่", "Age-Old", "古旧"],
  ["ร่วมสมัย", "Modern", "现代"],
  ["เรียบง่าย", "Simple", "简单"],
  ["ประดับ", "Ornate", "华丽"],
  ["ดิ่น", "Plain", "素净"],
  ["เหงา", "Lonely", "寂寞"],
  ["วุ่น", "Busy", "繁忙"],
  ["ว่างงาน", "Idle", "闲置"],
  ["กล้า", "Brave", "勇敢"],
  ["ขี้อาย", "Shy", "羞怯"],
  ["ภูมิใจ", "Proud", "骄傲"],
  ["ถ่อม", "Humble", "谦逊"],
  ["เล่น", "Playful", "嬉戏"],
  ["เคร่งขรึม", "Serious", "端肃"],
  ["ช่างปลอบ", "Soothing", "安抚"],
  ["กำมะหยี่", "Velvet", "天鹅绒"],
  ["ผลึก", "Crystal", "水晶"],
  ["อรุณอ้อย", "Honeyed", "蜜色"],
  ["ขรุม", "Rusty", "锈蚀"],
  ["สึก", "Worn", "磨旧"],
  ["สด", "Fresh", "清新"],
  ["แห้ง", "Dry", "干燥"],
  ["เปียก", "Wet", "湿润"],
  ["ป่า", "Wild", "野生"],
  ["อยู่", "Tame", "驯服"],
  ["แสวงหา", "Seeking", "寻求"],
  ["สลาย", "Broken", "破碎"],
  ["สมบูรณ์", "Whole", "完整"],
  ["หนัก", "Heavy", "沉重"],
  ["เบา", "Light", "轻盈"],
  ["ใกล้", "Near", "邻近"],
  ["เหนือน้ำ", "Upstream", "上游"],
  ["ปากน้ำ", "Downstream", "下游"],
  ["หนาว", "Wintry", "冬寒"],
  ["จม", "Sunken", "沉没"],
  ["ไม่หัก", "Unbroken", "不折"],
  ["เงียบงัน", "Hushed", "屏息"],
  ["ยาว", "Long", "悠长"],
  ["สั้น", "Brief", "短促"],
  ["คม", "Keen", "锐利"],
  ["นุ่มลื่น", "Smooth", "平滑"],
  ["คราวคลื่น", "Restless Sea", "起伏"],
];

export const NOUN = [
  ["แม่น้ำ", "River", "河"],
  ["อรุณ", "Dawn", "黎明"],
  ["สนธิ", "Dusk", "黄昏"],
  ["จันทร์", "Moon", "月"],
  ["ดาว", "Star", "星"],
  ["ฝน", "Rain", "雨"],
  ["หิมะ", "Snow", "雪"],
  ["หมอก", "Mist", "雾"],
  ["เมฆ", "Cloud", "云"],
  ["ลม", "Wind", "风"],
  ["ต้นสน", "Pine", "松"],
  ["ต้นหลิว", "Willow", "柳"],
  ["ไผ่", "Bamboo", "竹"],
  ["ดอกไม้", "Blossom", "梅"],
  ["ดอกบัว", "Lotus", "莲"],
  ["ภูเขา", "Mountain", "山"],
  ["เนิน", "Hill", "丘"],
  ["หุบเขา", "Valley", "谷"],
  ["ป่า", "Forest", "林"],
  ["สวน", "Garden", "园"],
  ["สะพาน", "Bridge", "桥"],
  ["ทาง", "Path", "路"],
  ["หิน", "Stone", "石"],
  ["หน้าต่าง", "Window", "窗"],
  ["ประตู", "Door", "门"],
  ["บันได", "Stair", "阶"],
  ["ตะเกียง", "Lamp", "灯"],
  ["เทียน", "Candle", "烛"],
  ["กระจก", "Mirror", "镜"],
  ["จดหมาย", "Letter", "信"],
  ["หน้ากระดาษ", "Page", "页"],
  ["หนังสือ", "Book", "书"],
  ["ขน", "Feather", "羽"],
  ["ปีก", "Wing", "翼"],
  ["ระฆัง", "Bell", "钟"],
  ["กลอง", "Drum", "鼓"],
  ["ขลุ่ย", "Flute", "笛"],
  ["อาร์ป", "Harp", "竖琴"],
  ["ไวโอลิน", "Violin", "小提琴"],
  ["เปียโน", "Piano", "钢琴"],
  ["ทำนอง", "Melody", "旋律"],
  ["ความเงียบ", "Silence", "寂静"],
  ["จังหวะ", "Rhythm", "节奏"],
  ["การประสาน", "Harmony", "和声"],
  ["การปิดท้าย", "Cadence", "收束"],
  ["วรรค", "Phrase", "乐句"],
  ["แนวทำนอง", "Theme", "主题"],
  ["ฝัน", "Dream", "梦"],
  ["การนอน", "Sleep", "睡眠"],
  ["ความทรงจำ", "Memory", "记忆"],
  ["คำมั่น", "Promise", "诺言"],
  ["การจาก", "Farewell", "告别"],
  ["การต้อนรับ", "Welcome", "迎候"],
  ["การเดินทาง", "Journey", "旅程"],
  ["การกลับ", "Return", "归来"],
  ["การมาถึง", "Arrival", "抵达"],
  ["การออกเดินทาง", "Departure", "启程"],
  ["หัวใจ", "Heart", "心"],
  ["ลมหายใจ", "Breath", "气息"],
  ["ความอบอุ่น", "Warmth", "暖意"],
  ["แสง", "Light", "光"],
  ["เงา", "Shadow", "影"],
  ["ไฟ", "Fire", "火"],
  ["เถ้า", "Ash", "灰"],
  ["ฝุ่น", "Dust", "尘"],
  ["น้ำ", "Water", "水"],
  ["คลื่น", "Wave", "浪"],
  ["ฟอง", "Foam", "泡沫"],
  ["น้ำแข็ง", "Ice", "冰"],
  ["ถ่าน", "Ember", "余烬"],
  ["เมล็ด", "Seed", "种子"],
  ["ราก", "Root", "根"],
  ["กิ่ง", "Branch", "枝"],
  ["ใบไม้", "Leaf", "叶"],
  ["กลีบ", "Petal", "瓣"],
  ["พัน", "Vine", "藤"],
  ["ทุ่ง", "Meadow", "草场"],
  ["พรุน", "Frost", "霜"],
  ["หยดน้ำ", "Dew", "露"],
  ["สีรุ้ง", "Rainbow", "彩虹"],
  ["ขอบฟ้า", "Horizon", "地平线"],
  ["ท้องฟ้า", "Sky", "天空"],
  ["ทะเล", "Sea", "海"],
  ["ท่าเรือ", "Harbour", "港"],
  ["เรือ", "Boat", "船"],
  ["ใบเรือ", "Sail", "帆"],
  ["หางเสือ", "Oar", "桨"],
  ["ประภาคาร", "Lighthouse", "灯塔"],
  ["เกาะ", "Island", "岛"],
  ["ต้นสัก", "Cedar", "雪松"],
  ["ใบเมเปิล", "Maple", "枫"],
  ["ฟิน", "Fern", "蕨"],
  ["หญ้าสามใบ", "Clover", "三叶草"],
  ["หนาม", "Thorn", "刺"],
  ["เช้า", "Morning", "晨"],
  ["เย็น", "Evening", "傍晚"],
  ["เที่ยงคืน", "Midnight", "午夜"],
  ["ฤดูใบไม้ร่วง", "Autumn", "秋"],
  ["ฤดูหนาว", "Winter", "冬"],
  ["ฤดูใบไม้ผลิ", "Spring", "春"],
  ["ฤดูร้อน", "Summer", "夏"],
  ["เพลง", "Song", "歌"],
  ["เสียง", "Voice", "声"],
  ["โน้ต", "Note", "音符"],
  ["คอร์ด", "Chord", "和弦"],
  ["ก้าว", "Step", "步"],
  ["วอลท์", "Waltz", "圆舞曲"],
  ["เรียบรรณ", "Aria", "咏叹调"],
  ["น็อกเทิร์น", "Nocturne", "夜曲"],
  ["เกตุ", "Etude", "练习曲"],
  ["อาทิต", "Prelude", "前奏曲"],
  ["บัลลาด", "Ballad", "叙事曲"],
  ["มาร์ช", "March", "进行曲"],
  ["ทำนองเดิน", "Walking Tune", "行板"],
  ["ริถี", "Rhyme", "韵"],
];

export const PLACE = [
  ["at dusk", "ยามสนธิ", "黄昏时"],
  ["at dawn", "ยามอรุณ", "黎明时"],
  ["in the rain", "ในฝน", "雨中"],
  ["in the snow", "ในหิมะ", "雪中"],
  ["in the mist", "ในหมอก", "雾中"],
  ["under the moon", "ใต้แสงจันทร์", "月下"],
  ["under the stars", "ใต้แสงดาว", "星空下"],
  ["on the hill", "บนเนิน", "山丘上"],
  ["on the river", "บนผืนน้ำ", "河面上"],
  ["beside the sea", "ริมทะเล", "海边"],
  ["beside the fire", "ข้างกองไฟ", "炉火旁"],
  ["behind the window", "หลังหน้าต่าง", "窗后"],
  ["beyond the bridge", "เลยสะพาน", "桥那头"],
  ["above the clouds", "เหนือเมฆ", "云上"],
  ["among the pines", "ท่ามกลางต้นสน", "松林中"],
  ["along the path", "ตามทาง", "路上"],
  ["near the water", "ใกล้น้ำ", "近水处"],
  ["before the dawn", "ก่อนอรุณ", "天明前"],
  ["after the rain", "หลังฝน", "雨后"],
  ["in the valley", "ในหุบเขา", "谷中"],
  ["in the garden", "ในสวน", "园中"],
  ["in the forest", "ในป่า", "林中"],
  ["on the stone", "บนหิน", "石上"],
  ["at the window", "ที่หน้าต่าง", "窗前"],
  ["at the door", "ที่ประตู", "门前"],
  ["by the lamp", "ข้างตะเกียง", "灯旁"],
  ["by the road", "ข้างทาง", "路旁"],
  ["through the leaves", "ท่ามกลางใบไม้", "叶间"],
  ["across the fields", "ข้ามทุ่ง", "田间"],
  ["along the shore", "ตามชายฝั่ง", "岸上"],
  ["in the harbour", "ในท่าเรือ", "港中"],
  ["on the sail", "บนใบเรือ", "帆上"],
  ["in the moonlight", "ในแสงจันทร์", "月光中"],
  ["in the lamplight", "ในแสงตะเกียง", "灯下"],
  ["in the first light", "ในแสงแรก", "初光中"],
  ["in the last light", "ในแสงสุดท้าย", "末光中"],
  ["at day's end", "เมื่อวันสิ้นสุด", "日暮时"],
  ["in an empty house", "ในบ้านที่ว่าง", "空屋中"],
  ["on a quiet street", "ในถนนเงียบ", "静街上"],
  ["at the edge of the world", "ที่สุดขอบโลก", "天涯"],
];